import {esc,fmt,signed,json,statusText,statusTone,tailLabel,changeValue as showField} from './format.js';
const FIELD_NAMES={stages:'Active stages',stage_charge_V:'Charge per stage',front_per_stage_ohm:'Front resistor / stage',tail_per_stage_ohm:'Tail resistor / stage',recipe_id:'Arrangement'};
export function mountAdjustment(container,{request,row,runId,api,isCurrent,onInspect,onDiscovery}){
  if(!row){container.innerHTML='<section class="card"><h2>No evaluated setting</h2><p>Run a complete catalog search first.</p></section>';return;}
  const seed={...row.configuration,...request.current_setting},isLI=request.impulse_type==='LI';
  // Inputs show a readable rounding; an untouched field still submits the exact stored value.
  const shown=(k,scale)=>Number((seed[k]/scale).toPrecision(9));
  const field=(k,label,unit,scale=1)=>`<div class="field"><label for="adj-${k}">${label}</label><div class="input-unit"><input id="adj-${k}" type="number" step="any" min="0" required inputmode="decimal" value="${shown(k,scale)}">${unit?`<span class="unit">${unit}</span>`:''}</div></div>`;
  const fact=(label,value)=>`<div><dt>${label}</dt><dd class="num">${value}</dd></div>`;
  container.innerHTML=`<div class="page-head"><div><div class="eyebrow">Evaluated alternatives · declared physical inventory</div><h1>Next Legal Adjustment</h1><p>Compare the setting actually erected on the generator with this request’s complete evaluated catalog.</p></div></div>
  <section class="card"><div class="card-head"><h3>Current generator setting</h3><span class="micro-inline">Pre-filled from the selected configuration #${row.rank}</span></div><form id="adjustment-form"><div class="fields five">${field('stages','Active stages','')}${field('stage_charge_V','Charge per stage','kV',1000)}${field('front_per_stage_ohm','Front resistor / stage','Ω')}${field('tail_per_stage_ohm','Tail resistor / stage','Ω')}<div class="field"><label for="adj-recipe">Arrangement</label><select id="adj-recipe"><option value="DEV_UNIFORM_SINGLE_v2">Single front and tail</option><option value="HYP_LI_TAIL_180_PAR_520_v1">LI tail 180 || 520 Ω</option></select></div></div>
  <div class="form-foot"><div class="fixed-request"><span class="fixed-label">Fixed request</span><dl class="run-facts">${fact('Impulse',esc(request.impulse_type))}${fact('Crest',`${fmt(request.target_crest_V,1000)} kV`)}${fact('DUT',`${fmt(request.setup.dut_capacitance_F,1e-12)} pF`)}${fact('Loop L',`${fmt(request.setup.loop_inductance_H,1e-6)} µH`)}</dl><p class="micro">Only the generator setting is compared; the request inputs stay unchanged.</p></div><button type="submit" class="btn primary">Find next permitted adjustment</button></div></form><div id="adjustment-error" role="alert"></div></section>
  <div id="adjustment-result"></div>
  <section class="card"><div class="card-head"><h3>Informative next evidence</h3><span class="micro-inline">Questions whose answers would most reduce uncertainty</span></div><div id="next-measurement" class="qa-list"><div class="loading">Loading engineering questions…</div></div></section>`;
  container.querySelector('#adj-recipe').value=seed.recipe_id;
  api(`/api/runs/${runId}/next-measurement`).then(r=>{if(isCurrent())container.querySelector('#next-measurement').innerHTML=r.items.map(x=>`<details><summary>${esc(x.question)}</summary><p>${esc(x.action)}</p><p class="small muted">${esc(x.resolves)}</p></details>`).join('')||'<p class="muted small">No open questions recorded.</p>';}).catch(e=>{if(isCurrent())container.querySelector('#next-measurement').textContent=e.message;});
  const metricRows=(result,r)=>[['Crest','crest_magnitude_V',1000,'kV'],[isLI?'T1':'Tp',isLI?'T1_s':'Tp_s',1e-6,'µs'],['T2','T2_s',1e-6,'µs']].map(([label,k,scale,unit])=>{const d=r.expected_minus_current?.[k];return `<tr><td>${label} <small class="muted">${unit}</small></td><td class="r num">${fmt(result.current.physics_reference?.metrics?.[k],scale)}</td><td class="r num"><b>${fmt(r.expected_metrics?.[k],scale)}</b></td><td class="r num">${Number.isFinite(d)?signed(d/scale,3):'—'}</td></tr>`;}).join('');
  const option=(result,r,i)=>{const c=r.configuration,st=r.assessment.compliance_status;return `<section class="card adjustment-option"><div class="card-head"><span class="kicker">${i===0?'Next considered setting':`Alternative ${i+1}`}</span><span class="chip ${statusTone(st)}">${esc(statusText(st))}</span></div>
    <div class="option-hero"><div><h3 class="option-title"><span class="num">${c.stages}</span> stages × <span class="num">${fmt(c.stage_charge_V,1000)}</span> kV</h3><p class="muted">Front <span class="num">${fmt(c.front_per_stage_ohm)}</span> Ω · tail <span class="num">${tailLabel(c)}</span> Ω per stage</p></div><div class="option-count"><b class="num">${r.hardware_changes}</b><small>hardware field${r.hardware_changes===1?'':'s'} changed</small></div></div>
    <div class="grid-2 inner"><div><h4>Changes from the current setting</h4>${r.changes.length?`<dl class="kvs tight">${r.changes.map(x=>`<div class="kv"><dt>${esc(FIELD_NAMES[x.field]??x.field.replaceAll('_',' '))}</dt><dd class="num">${showField(x.field,x.before)} → <b>${showField(x.field,x.after)}</b></dd></div>`).join('')}</dl>`:'<p class="muted small">No setting fields change.</p>'}
    <h4>Tolerance position</h4><dl class="kvs tight">${Object.entries(r.score?.components??{}).map(([k,x])=>`<div class="kv"><dt>${k==='crest'?'Crest':k.replace('_s','')}</dt><dd class="num ${x.within_limits?'':'out-text'}">${signed(x.deviation_pct,2)} % from target · ${x.within_limits?'inside':'outside'}</dd></div>`).join('')}</dl></div>
    <div><h4>Expected waveform</h4><div class="table-wrap"><table class="data compact"><thead><tr><th>Parameter</th><th class="r">Current setting</th><th class="r">After adjustment</th><th class="r">Change</th></tr></thead><tbody>${metricRows(result,r)}</tbody></table></div></div></div>
    <div class="actions"><button type="button" class="btn sm" data-adjust-inspect="${esc(r.candidate_id)}">Inspect evaluated waveform</button><button type="button" class="btn ghost sm" data-adjust-discover="${i}">Explore this fixed setting</button></div>
    <details class="expert-block"><summary>Component list and declared constraints</summary>${json(r.component_bill_of_materials)}${json(r.hard_constraints)}</details></section>`;};
  container.querySelector('#adjustment-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;const error=container.querySelector('#adjustment-error');error.textContent='';try{const scales={stage_charge_V:1000},val=k=>{const raw=container.querySelector('#adj-'+k).value,sc=scales[k]??1;return Number(raw)===shown(k,sc)?seed[k]:Number(raw)*sc;},c={...seed,stages:val('stages'),stage_charge_V:val('stage_charge_V'),front_per_stage_ohm:val('front_per_stage_ohm'),tail_per_stage_ohm:val('tail_per_stage_ohm'),recipe_id:container.querySelector('#adj-recipe').value};const result=await api(`/api/runs/${runId}/next-adjustment`,{configuration:c});if(!isCurrent())return;const out=container.querySelector('#adjustment-result');
    out.innerHTML=`<div class="result-head"><h2>${result.passing_alternative_exists?'A passing numerical alternative is available':'No passing alternative in this catalog'}</h2><span class="micro-inline">${result.catalog_count} configurations evaluated</span></div><p class="result-policy">${esc(result.policy)}</p>${result.alternatives.map((r,i)=>option(result,r,i)).join('')||'<section class="card"><p class="muted">No different evaluable settings in the declared inventory.</p></section>'}`;
    out.querySelectorAll('[data-adjust-inspect]').forEach(b=>b.addEventListener('click',()=>onInspect(b.dataset.adjustInspect)));out.querySelectorAll('[data-adjust-discover]').forEach(b=>b.addEventListener('click',()=>onDiscovery(result.alternatives[Number(b.dataset.adjustDiscover)].configuration)));}catch(e){if(isCurrent())error.innerHTML=`<div class="note fail">${esc(e.message)}</div>`;}finally{button.disabled=false;}});
}
