// Presentation controller. All engineering values come from the local API unchanged.
import {tailLabel,esc,fmt,json,date,reasonList,readForm,MV} from './format.js';
import * as view from './views.js';
import {drawWaveform} from './waveform.js';
import {mountScenarioScreen} from './scenarios.js';
import {renderImported} from './imports.js';
import {mountDiscovery} from './discovery.js';
import {mountAdjustment} from './adjustment.js';
import {equipmentDetails} from './equipment.js';

const UI_VERSION='1.0.0';
const RUN_SCREENS=['result','alternatives','waveform','evidence','search','screening','adjustment'];
const discoveryMemory={};
const state={selectionGeneration:0,meta:null,screen:'plan',lastRunScreen:'result',bundle:null,row:null,range:'tail',markers:true,compareId:null,overlayRange:'tail',draft:null,annotations:{},waves:new Map(),measurement:null,history:null,historyFilter:{type:'all',source:'all',text:''}};
const main=document.getElementById('main'),modal=document.getElementById('modal');
let renderToken=0,toastTimer,pollTimer,draws=new Map();

async function api(path,data){const options=data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)};const response=await fetch(path,options);const payload=await response.json();if(!response.ok)throw new Error(payload.error??'Local request failed');return payload;}
function toast(message,tone=''){const el=document.getElementById('toast');el.textContent=message;el.className=tone;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5200);}
function showModal(title,description,body,footer='',wide=false){document.getElementById('modal-content').innerHTML=`<div class="modal-header"><div><h2 id="modal-title">${esc(title)}</h2><p>${esc(description)}</p></div><button class="icon-btn" data-action="close" aria-label="Close dialog">${view.icon('close')}</button></div><div class="modal-body">${body}</div>${footer?`<div class="modal-footer">${footer}</div>`:''}`;modal.classList.toggle('wide',wide);if(!modal.open)modal.showModal();}
function close(){modal.close();}
function preserveDraft(){if(document.getElementById('test-form')){const form=readForm(state.draft??state.meta.default_request);state.draft=form.request;state.annotations=form.annotations;}}
function navigate(screen){preserveDraft();if(screen!==state.screen){main.classList.add('enter');setTimeout(()=>main.classList.remove('enter'),260);}state.screen=screen;if(RUN_SCREENS.includes(screen))state.lastRunScreen=screen;if(location.hash.slice(1)!==screen)history.replaceState(null,'','#'+screen);render();window.scrollTo({top:0});}
function selectRow(id){state.row=state.bundle?.result?.candidates.find(r=>r.candidate_id===id)??state.row;}
const primaryRow=p=>p?.best_configuration??p?.closest_noncompliant??p?.candidates?.[0]??null;
function selectedRequest(){return state.bundle?.result?.request??state.meta.default_request;}
function scenarioToRequest(scenario){
  const c=scenario.configuration,q=structuredClone(state.meta.default_request);
  Object.assign(q,{request_id:'SCENARIO_'+new Date().toISOString().slice(0,19),impulse_type:c.impulse_type,topology_id:c.topology_id,polarity:c.polarity??1,target_crest_V:scenario.target_crest_V,setup:structuredClone(scenario.setup),catalog_scope:'development',recipe_ids:[c.recipe_id],current_setting:Object.fromEntries(['stages','stage_charge_V','front_per_stage_ohm','tail_per_stage_ohm','recipe_id'].map(k=>[k,c[k]]))});
  state.draft=q;state.annotations={notes:'Explicitly copied from a selected exploration/actual setting. Review setup before running the complete catalog.'};navigate('plan');toast('Scenario copied into a separate request. Review inputs before optimization.');
}
function bindReopen(){document.getElementById('reopen-bundle').addEventListener('click',async e=>{const button=e.currentTarget,error=document.getElementById('reopen-error'),file=document.getElementById('reopen-file').files[0];if(!file){error.textContent='Select a complete evidence ZIP.';return;}if(file.size>200_000_000){error.textContent='Maximum ZIP size is 200 MB.';return;}button.disabled=true;const token=state.selectionGeneration,viewToken=renderToken;try{const response=await fetch('/api/reopen',{method:'POST',headers:{'Content-Type':'application/zip'},body:file}),data=await response.json();if(!response.ok)throw new Error(data.error);if(token!==state.selectionGeneration||viewToken!==renderToken)return;await openRun(data.run_id);toast('Complete evidence bundle reopened, including imported waveforms.');}catch(e){error.textContent=e.message;}finally{button.disabled=false;}});}

function chrome(){
  const group=RUN_SCREENS.includes(state.screen)?'run':state.screen;
  document.querySelectorAll('[data-nav]').forEach(el=>{const on=el.dataset.nav===group;el.classList.toggle('active',on);on?el.setAttribute('aria-current','page'):el.removeAttribute('aria-current');});
  document.getElementById('export-button').disabled=!state.bundle?.result;
  const runNav=document.querySelector('[data-nav="run"] .nav-dot');if(runNav)runNav.hidden=!state.bundle;
}

async function render(){
  if(!state.meta)return;const token=++renderToken;chrome();draws.clear();
  if(state.opening){main.innerHTML=view.loading();return;}
  try{
    if(state.screen==='plan'){main.innerHTML=view.plan(state);bindPlan();return;}
    if(state.screen==='discovery'){
      const q=state.bundle?.result?.request??state.draft??state.meta.default_request;
      const c=state.row?.configuration??{impulse_type:q.impulse_type,stages:10,stage_charge_V:150000,front_per_stage_ohm:3700,tail_per_stage_ohm:5000,topology_id:q.topology_id,polarity:q.polarity??1,recipe_id:'DEV_UNIFORM_SINGLE_v2'};
      mountDiscovery(main,{seed:{configuration:c,setup:q.setup,target_crest_V:q.target_crest_V},api,isCurrent:()=>token===renderToken,memory:discoveryMemory,onOptimize:scenarioToRequest});return;
    }
    if(state.screen==='history'){main.innerHTML=view.loading();state.history=await api('/api/runs');if(token!==renderToken)return;main.innerHTML=view.historyView(filterHistory(),state.bundle?.run.run_id)+'<section class="card"><h3>Reopen a complete evidence bundle</h3><p>Restore the original result, raw traces, metadata and diagnostics from an exported ZIP.</p><div class="form-foot"><input id="reopen-file" type="file" accept=".zip" aria-label="Evidence ZIP"><button id="reopen-bundle" class="btn">Reopen evidence</button></div><div id="reopen-error" role="alert"></div></section>';bindHistory();bindReopen();return;}
    if(state.screen==='measured'){main.innerHTML=view.measuredView(state);bindMeasurement();await savedMeasurements();if(state.measurement)showMeasurement();return;}
    if(!RUN_SCREENS.includes(state.screen)){state.screen='plan';return render();}
    if(!state.bundle){main.innerHTML=view.empty(state.meta);return;}
    if(['QUEUED','RUNNING'].includes(state.bundle.run.status)){main.innerHTML=view.runFrame(state)+view.progressView(state.bundle);return;}
    if(state.bundle.run.status==='FAILED'){main.innerHTML=view.runFrame(state)+`<section class="verdict fail"><div class="verdict-ic">${view.icon('cross',26)}</div><div class="verdict-body"><div class="eyebrow">Execution failed</div><h1>The optimisation could not complete</h1><p>No partial result has been promoted. Review the request and run again.</p></div></section><section class="card">${json(state.bundle.run.error)}<div class="actions"><button class="btn primary" data-action="edit">Review the request</button></div></section>`;return;}
    const result=state.bundle.result;if(!result){main.innerHTML=view.empty(state.meta);return;}
    if(state.bundle.artifact_compatibility!=='MATCHES_CURRENT_STACK')toast('This record uses a different prediction stack. It is shown as a historical result, not a new validation.');
    const frame=view.runFrame(state);
    if(state.screen==='adjustment'){main.innerHTML=frame+'<div id="adjustment"></div>';mountAdjustment(document.getElementById('adjustment'),{request:result.request,row:state.row,runId:state.bundle.run.run_id,api,isCurrent:()=>token===renderToken,onInspect:id=>{selectRow(id);navigate('result');},onDiscovery:c=>{discoveryMemory.scenario={configuration:c,setup:structuredClone(result.request.setup),target_crest_V:result.request.target_crest_V};discoveryMemory.record=null;discoveryMemory.prediction=null;navigate('discovery');}});return;}
    if(state.screen==='result'){main.innerHTML=frame+view.resultView(state);if(state.row?.waveform_reference)await plotWave('result-wave',{range:'tail',height:300},token);await whyCompare(token);return;}
    if(state.screen==='alternatives'){if(result.candidates.length>1)state.compareId=state.compareId&&state.compareId!==result.candidates[0].candidate_id?state.compareId:result.candidates[1].candidate_id;main.innerHTML=frame+view.alternatives(state);if(result.candidates.length>1){document.getElementById('compare-choice').addEventListener('change',event=>{state.compareId=event.target.value;render();});await loadComparison(token);}return;}
    if(state.screen==='waveform'){main.innerHTML=frame+view.waveformView(state);bindWaveform();if(state.row?.waveform_reference)await plotWave('analysis-wave',{range:state.range,height:440,markers:state.markers,zoom:true},token);return;}
    if(state.screen==='evidence'){if(!state.row){main.innerHTML=frame+view.resultView(state);return;}main.innerHTML=frame+view.evidenceView(state);const e=await api(`/api/runs/${state.bundle.run.run_id}/evidence?candidate=${state.row.candidate_id}`);if(token===renderToken)document.getElementById('evidence-content').innerHTML=view.evidenceContent(e,state);return;}
    if(state.screen==='screening'){navigate('discovery');return;}
    if(state.screen==='search'){main.innerHTML=frame+view.searchView(state);bindSearch();return;}
  }catch(error){if(token===renderToken)main.innerHTML=`<section class="verdict fail"><div class="verdict-ic">${view.icon('warn',24)}</div><div class="verdict-body"><div class="eyebrow">Local evidence error</div><h1>The saved evidence could not be loaded</h1><p>${esc(error.message)}</p><div class="actions"><button class="btn" data-action="history">Open saved runs</button></div></div></section>`;}
}

/* ------------------------------------------------------------------ waveforms */
async function getWave(id){const key=`${state.bundle.run.run_id}:${id}`;if(!state.waves.has(key)){state.waves.set(key,await api(`/api/runs/${state.bundle.run.run_id}/waveform?candidate=${id}`));if(state.waves.size>24)state.waves.delete(state.waves.keys().next().value);}return state.waves.get(key);}
async function plotWave(elementId,{range,height,markers=true,zoom=false,extra=null},token){
  const row=state.row,wave=await getWave(row.candidate_id);const series=[{wave,label:`#${row.rank} reference`,kind:'reference'}];
  if(wave.target)series.push({wave:wave.target,label:'Mathematical nominal target',kind:'target'});
  if(extra)series.push(...extra);const el=document.getElementById(elementId);if(token!==renderToken||!el)return;
  const args={series,request:selectedRequest(),row,range,height,markers,onZoom:zoom?(r=>{state.range=r??'tail';render();}):null};
  draws.set(elementId,args);drawWaveform(el,args);
}
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>draws.forEach((args,id)=>{const el=document.getElementById(id);if(el)drawWaveform(el,args);}),120);});

/* ------------------------------------------------------------------ plan */
function bindPlan(){
  const form=document.getElementById('test-form'),p=state.meta.profile;
  const refresh=()=>{try{const f=readForm(state.draft??state.meta.default_request);document.getElementById('test-sheet').innerHTML=view.testSheet(f.request,p);document.getElementById('schematic').innerHTML=view.schematic(f.request.topology_id,f.request.setup,p.capacitors.basic_load_capacitance.value);document.getElementById('target-mv').textContent=MV(f.request.target_crest_V);}catch{}};
  form.addEventListener('input',refresh);form.addEventListener('change',refresh);
  document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{preserveDraft();if(state.draft.impulse_type!==b.dataset.mode){delete state.draft.available_tail_per_stage_ohm;state.draft.recipe_ids=['DEV_UNIFORM_SINGLE_v2'];state.draft.request_id=state.draft.request_id.replace(/^(LI|SI)_/,b.dataset.mode+'_');}state.draft.impulse_type=b.dataset.mode;render();}));
  document.querySelectorAll('[data-polarity]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('polarity').value=b.dataset.polarity;document.querySelectorAll('[data-polarity]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});refresh();}));
  const toggle=()=>{const checked=document.getElementById('use-current').checked;document.getElementById('current-fields').hidden=!checked;document.querySelectorAll('#current-fields input,#current-fields select').forEach(el=>el.disabled=!checked);};toggle();document.getElementById('use-current').addEventListener('change',toggle);
  form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;if(button)button.disabled=true;document.getElementById('form-error').innerHTML='';try{const f=readForm(state.draft??state.meta.default_request);const validated=await api('/api/validate',f);state.draft=validated.request;state.annotations=validated.annotations;review(validated);}catch(error){document.getElementById('form-error').innerHTML=`<div class="note fail">${view.icon('warn',15)}<span><b>The request was not accepted.</b> ${esc(error.message)}</span></div>`;document.getElementById('form-error').scrollIntoView({block:'center',behavior:'smooth'});}finally{if(button)button.disabled=false;}});
}
function review(validated){const q=validated.request,s=q.setup,prov=validated.annotations.value_provenance??{};const row=(l,v,k)=>`<div class="kv"><dt>${l}</dt><dd><span class="num">${v}</span>${k&&prov[k]?` <span class="prov-chip ${prov[k]}">${esc(prov[k])}</span>`:''}</dd></div>`;
  showModal('Review the fixed test setup','These conditions are passed to the optimiser unchanged. Only stages, charge and resistor recipe are searched.',`<div class="review"><div class="target-strip">${view.targetStrip(state.meta.profile,q.impulse_type)}</div><div class="grid-2 inner"><dl class="kvs">${row('Requested crest',`${q.polarity===1?'+':'−'}${fmt(q.target_crest_V,1000)} kV · ${MV(q.target_crest_V)}`,'target_crest_V')}${row('DUT capacitance',`${fmt(s.dut_capacitance_F,1e-12)} pF`,'dut_capacitance_F')}${row('Divider capacitance',`${fmt(s.divider_capacitance_F,1e-12)} pF`,'divider_capacitance_F')}${row('Stray capacitance',`${fmt(s.stray_capacitance_F,1e-12)} pF`,'stray_capacitance_F')}${row('Loop inductance',`${fmt(s.loop_inductance_H,1e-6)} µH`,'loop_inductance_H')}${row('Basic C coverage',esc(s.basic_coverage_assumption))}</dl><dl class="kvs">${row('Equipment profile',esc(q.equipment_profile_id))}${row('Declared topology',esc(q.topology_id))}${row('Recipe scope',esc(q.catalog_scope))}${row('Circuit arrangements',(q.recipe_ids??[]).map(esc).join('<br>')||'None selected')}${row('Available resistors',view.inventorySummary(q))}${row('Candidate space',`${validated.catalog_count} configurations, exhaustive`)}${row('Current setting',q.current_setting?`${q.current_setting.stages} stages · ${fmt(q.current_setting.stage_charge_V,1000)} kV`:'Not supplied')}</dl></div>${validated.previous_exact_cases.length?`<div class="note">${view.icon('history',15)}<span><b>This exact request was run before.</b> ${validated.previous_exact_cases.map(r=>`<button class="btn link" data-open-run="${r.run_id}">${date(r.created_at)} · ${r.same_stack?'same stack':'different stack'}</button>`).join(' ')}</span></div>`:''}</div>`,`<button class="btn ghost" data-action="close">Back to setup</button><button class="btn primary" data-action="run">${view.icon('play',14)} Run complete optimisation</button>`);}
async function startRun(){const button=document.querySelector('[data-action="run"]');if(button)button.disabled=true;const token=beginSelection('new-search'),openingRender=renderToken;try{const run=await api('/api/runs',{request:state.draft,annotations:state.annotations});if(token!==state.selectionGeneration)return;close();state.opening=null;state.bundle={run,result:null};remember(run.run_id);if(openingRender===renderToken)navigate('result');else render();pollRun(run.run_id,token);}catch(error){if(token===state.selectionGeneration){state.opening=null;render();toast(error.message,'error');if(button)button.disabled=false;}}}
async function pollRun(id,token=state.selectionGeneration){if(token!==state.selectionGeneration||state.bundle?.run.run_id!==id)return;clearTimeout(pollTimer);try{const bundle=await api(`/api/runs/${id}`);if(token!==state.selectionGeneration||state.bundle?.run.run_id!==id)return;state.bundle=bundle;if(bundle.result){state.row=primaryRow(bundle.result);state.compareId=null;state.range='tail';if(RUN_SCREENS.includes(state.screen))render();toast('Complete search saved with its reference waveforms.');}else if(RUN_SCREENS.includes(state.screen))render();if(['QUEUED','RUNNING'].includes(bundle.run.status))pollTimer=setTimeout(()=>pollRun(id,token),1200);}catch(error){if(token===state.selectionGeneration&&state.bundle?.run.run_id===id){toast(error.message,'error');pollTimer=setTimeout(()=>pollRun(id,token),3000);}}}
function remember(id){try{localStorage.setItem('powernext-run',id);}catch{}}
function beginSelection(label){const token=++state.selectionGeneration;clearTimeout(pollTimer);++renderToken;draws.clear();state.opening=label;state.bundle=null;state.row=null;state.measurement=null;state.waves.clear();main.innerHTML=view.loading();document.getElementById('export-button').disabled=true;return token;}
async function openRun(id,screen='result',token=null){if(token===null)token=beginSelection(id);if(token!==state.selectionGeneration)return;close();state.opening=id;const openingRender=renderToken;let incoming;try{incoming=await api(`/api/runs/${id}`);}catch(error){if(token!==state.selectionGeneration)return;state.opening=null;render();throw error;}if(token!==state.selectionGeneration)return;state.opening=null;state.bundle=incoming;state.row=primaryRow(incoming.result);state.compareId=null;state.range='tail';state.measurement=null;remember(id);if(openingRender===renderToken)navigate(screen);else render();if(!incoming.result&&['QUEUED','RUNNING'].includes(incoming.run.status))pollRun(id,token);}
async function openDemo(id){const token=beginSelection('demo:'+id),openingRender=renderToken;document.querySelectorAll('[data-demo]').forEach(el=>el.disabled=true);try{const run=await api(`/api/demos/${id}`,{});if(token!==state.selectionGeneration)return;await openRun(run.run_id,openingRender===renderToken?(RUN_SCREENS.includes(state.screen)?state.screen:'result'):state.screen,token);if(token!==state.selectionGeneration)return;const d=state.meta.demonstrations.find(x=>x.id===id);if(d?.focus_candidate_id&&RUN_SCREENS.includes(state.screen)){selectRow(d.focus_candidate_id);navigate(id==='li_disagreement'?'evidence':'result');}toast(`Opened “${d?.title}” — a saved simulation record.`);}catch(error){if(token===state.selectionGeneration){state.opening=null;render();toast(error.message,'error');}}finally{if(token===state.selectionGeneration){document.querySelectorAll('[data-demo]').forEach(el=>el.disabled=false);const j=document.getElementById('scenario-jump');if(j)j.value=id;}}}
function demos(){showModal('Example cases','Saved optimiser evidence. Each case keeps its original waveforms, ranking and limitations.',view.demoLibrary(state.meta.demonstrations),'',true);}
function boundaries(){showModal('Equipment Profile & Technical Details','Confirmed ratings, declared circuit assumptions and source traceability.',equipmentDetails(state.meta),'',true);}
function exports(){if(!state.bundle?.result)return;const id=state.bundle.run.run_id;showModal('Export the engineering record','The original optimiser result is preserved byte-for-byte.',`<div class="export-list">${[['json','Structured JSON','Original result bytes, full ranking, models, constraints and relative waveform references.'],['html','Printable engineering report','Standalone HTML with the reference waveform, shortlist, Physics/ML comparison and evidence limits. Print to PDF from the browser.'],['zip','Complete evidence bundle','Result, request, run metadata, report, every hashed waveform and all imported raw traces, metadata and diagnostics. Reopen this ZIP from History.']].map(([f,t,d])=>`<a href="/api/runs/${id}/export?format=${f}" download>${view.icon('down',18)}<span><b>${t}</b><small>${d}</small></span><code>.${f}</code></a>`).join('')}</div>`);}

async function whyCompare(token){const p=state.bundle.result,el=()=>document.getElementById('why-compare');if(!el()||p.candidates.length<2)return el()&&(el().innerHTML='');const a=p.candidates[0],b=p.candidates[1];try{const e=await api(`/api/runs/${state.bundle.run.run_id}/compare?left=${a.candidate_id}&right=${b.candidate_id}`);if(token===renderToken&&el())el().innerHTML=`<div class="why-banner sm">${view.icon('compare',16)}<div><small>Versus runner-up #${b.rank} (${b.configuration.stages} stages, ${b.configuration.front_per_stage_ohm}/${tailLabel(b)} Ω)</small>${view.whySentence(a,b,p,e)}</div></div>`;}catch{if(el())el().innerHTML='';}}
async function loadComparison(token){const p=state.bundle.result,a=p.candidates[0],b=p.candidates.find(r=>r.candidate_id===state.compareId)??p.candidates[1];const explanation=await api(`/api/runs/${state.bundle.run.run_id}/compare?left=${a.candidate_id}&right=${b.candidate_id}`);const el=document.getElementById('pair-comparison');if(token!==renderToken||!el)return;el.innerHTML=view.comparison(a,b,p,explanation);
  const draw=async range=>{const box=document.getElementById('compare-wave');if(!box)return;if(!a.waveform_reference||!b.waveform_reference){box.innerHTML='<p class="muted small">One of these configurations has no evaluable waveform artifact.</p>';return;}const [wa,wb]=await Promise.all([getWave(a.candidate_id),getWave(b.candidate_id)]);if(token!==renderToken)return;const args={series:[{wave:wa,label:`#${a.rank}`,kind:'reference'},{wave:wb,label:`#${b.rank}`,kind:'alternative'}],request:p.request,row:a,range,height:300,markers:false};draws.set('compare-wave',args);drawWaveform(box,args);};
  el.querySelectorAll('[data-overlay-range]').forEach(btn=>btn.addEventListener('click',()=>{el.querySelectorAll('[data-overlay-range]').forEach(x=>x.classList.toggle('active',x===btn));state.overlayRange=btn.dataset.overlayRange;draw(btn.dataset.overlayRange);}));
  el.querySelectorAll('[data-overlay-range]').forEach(x=>x.classList.toggle('active',x.dataset.overlayRange===state.overlayRange));await draw(state.overlayRange);}

function bindWaveform(){document.getElementById('wave-candidate')?.addEventListener('change',e=>{selectRow(e.target.value);state.range='tail';render();});document.getElementById('toggle-markers')?.addEventListener('change',e=>{state.markers=e.target.checked;render();});}
function bindSearch(){const p=state.bundle.result,f=document.getElementById('search-filter'),st=document.getElementById('search-stages'),so=document.getElementById('search-sort');
  const apply=()=>{let rows=p.candidates.filter(r=>(f.value==='all'||r.assessment.compliance_status===f.value)&&(st.value==='all'||String(r.configuration.stages)===st.value));const key={J:r=>r.score?.J??Infinity,t2:r=>Math.abs(r.score?.components?.T2_s?.deviation_pct??Infinity),energy:r=>r.hard_constraints.total_energy_J??Infinity,stages:r=>r.configuration.stages}[so.value];if(key)rows=[...rows].sort((a,b)=>key(a)-key(b)||a.rank-b.rank);document.getElementById('search-table').innerHTML=view.candidateTable(rows,p,{expert:true,selected:state.row?.candidate_id});document.getElementById('search-note').textContent=`Showing ${rows.length} of ${p.candidates.length}${so.value!=='rank'?' · display sort only':''}. The rank column is always the optimizer's original order.`;};
  [f,st,so].forEach(x=>x.addEventListener('change',apply));}

/* ------------------------------------------------------------------ history */
function filterHistory(){const f=state.historyFilter,t=f.text.toLowerCase();return (state.history??[]).filter(r=>(f.type==='all'||r.request?.impulse_type===f.type)&&(f.source==='all'||r.source===f.source)&&(!t||`${r.request?.request_id} ${r.request?.topology_id} ${r.request?.equipment_profile_id}`.toLowerCase().includes(t)));}
function bindHistory(){const f=state.historyFilter,upd=()=>document.getElementById('history-rows').innerHTML=view.historyRows(filterHistory(),state.bundle?.run.run_id);
  document.querySelectorAll('[data-history-type]').forEach(b=>{b.classList.toggle('active',b.dataset.historyType===f.type);b.addEventListener('click',()=>{f.type=b.dataset.historyType;document.querySelectorAll('[data-history-type]').forEach(x=>x.classList.toggle('active',x===b));upd();});});
  const src=document.getElementById('history-source'),txt=document.getElementById('history-search');src.value=f.source;txt.value=f.text;src.addEventListener('change',()=>{f.source=src.value;upd();});txt.addEventListener('input',()=>{f.text=txt.value;upd();});}
async function compareRun(id){const previous=await api(`/api/runs/${id}`),current=state.bundle;if(!current?.result||!previous.result)return;const columns=[previous,current].map((bundle,i)=>{const p=bundle.result,r=p.best_configuration??p.closest_noncompliant;return `<section class="run-col ${i?'now':''}"><small class="kicker">${i?'Currently open':'Previously saved'} · ${date(bundle.run.created_at)}</small><h3>${esc(p.request.request_id)}</h3><p class="num small">${p.request.impulse_type} · ${fmt(p.request.target_crest_V,1000)} kV · DUT ${fmt(p.request.setup.dut_capacitance_F,1e-12)} pF · L ${fmt(p.request.setup.loop_inductance_H,1e-6)} µH</p>${p.best_configuration?`<span class="chip pass">${view.icon('check',13)}Compliant setting</span>`:`<span class="chip fail">${view.icon('cross',13)}No solution</span>`} <span class="chip neutral">Model prediction</span>${r?`<div class="run-col-setting"><b class="num">${r.configuration.stages}</b> stages × <b class="num">${fmt(r.configuration.stage_charge_V,1000)}</b> kV · ${r.configuration.front_per_stage_ohm}/${tailLabel(r)} Ω${p.best_configuration?'':' <small>(closest, not recommended)</small>'}</div>${view.metricsBlock(r,p)}`:'<p class="muted">No evaluable configuration</p>'}<dl class="kvs tight"><div class="kv"><dt>Profile</dt><dd>${esc(p.request.equipment_profile_id)}</dd></div><div class="kv"><dt>Topology</dt><dd>${esc(p.request.topology_id)}</dd></div><div class="kv"><dt>Optimizer</dt><dd>${esc(p.optimizer_version)}</dd></div><div class="kv"><dt>Model</dt><dd><code>${esc(r?.prediction?.model_id??'Fallback / unavailable')}</code></dd></div></dl><details class="expert-block"><summary>Original request & reason codes</summary>${json(p.request)}${reasonList(r?.reason_codes)}</details></section>`;});const same=current.result.stack_sha256===previous.result.stack_sha256;showModal('Compare saved engineering runs',same?'Same recorded prediction stack; different requests remain distinct records.':'Different stack versions. Historical outcomes are not silently revalidated.',`<div class="grid-2 inner">${columns.join('')}</div><p class="micro">Saved runs retain their recorded inputs and results.</p>`,'',true);}

/* ------------------------------------------------------------------ measured data */
function bindMeasurement(){
  const token=renderToken,runId=state.bundle?.run?.run_id,current=()=>token===renderToken&&runId===state.bundle?.run?.run_id;
  let originalMetadata=null,metadataLoad=0;
  document.getElementById('measurement-metadata').addEventListener('change',async event=>{const load=++metadataLoad,f=event.target.files[0];if(f){const text=await f.text();if(current()&&load===metadataLoad){const editor=document.getElementById('measurement-json');editor.value=text;originalMetadata={text,editorValue:editor.value};}}});
  document.getElementById('measurement-csv').addEventListener('change',e=>{const f=e.target.files[0],lab=e.target.closest('.drop');if(f&&lab)lab.querySelector('span').textContent=`${f.name} · ${fmt(f.size/1024,1,1)} kB`;});
  document.getElementById('import-measurement').addEventListener('click',async event=>{
    const button=event.currentTarget,err=document.getElementById('measurement-error');err.innerHTML='';button.disabled=true;
    try{if(!runId)throw new Error('Open a saved engineering request before attaching its acquisition evidence.');
      const file=document.getElementById('measurement-csv').files[0];if(!file)throw new Error('Select a CSV waveform export.');if(file.size>10_000_000)throw new Error('Maximum CSV size is 10 MB.');
      const editorText=document.getElementById('measurement-json').value,metadata_text=originalMetadata&&editorText===originalMetadata.editorValue?originalMetadata.text:editorText;let metadata;try{metadata=JSON.parse(metadata_text);}catch{throw new Error('Acquisition metadata is not valid JSON.');}
      const bytes=new Uint8Array(await file.arrayBuffer());if(!current())return;let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));
      const imported=await api(`/api/runs/${runId}/measurements`,{csv_base64:btoa(binary),metadata,metadata_text});if(!current())return;
      const record=await api(`/api/runs/${runId}/measurement/${imported.measurement_id}`);if(!current())return;
      state.measurement={...record,measurement_id:imported.measurement_id};showMeasurement();await savedMeasurements();if(current())toast('Raw waveform, metadata and diagnostics saved.');
    }catch(error){if(current())err.innerHTML=`<div class="note fail">${esc(error.message)}</div>`;}finally{button.disabled=false;}
  });
}
function measurementTemplate(){const p=state.bundle?.result,q=p?.request??state.meta.default_request,r=state.row;const template={shot_id:'',setup_id:q.setup.setup_id,shot_series_id:'',acquisition_time_utc:'',source_organization:document.getElementById('evidence-kind')?.value==='ACTUAL_LABORATORY_EXPORT'?'CPRI':'REPLACE_WITH_SOURCE',configuration:r?.configuration??{impulse_type:q.impulse_type,stages:null,stage_charge_V:null,front_per_stage_ohm:null,tail_per_stage_ohm:null,recipe_id:'',topology_id:q.topology_id},setup:q.setup,measurement:{time_column:'time',voltage_column:'voltage',time_unit:'us',voltage_unit:'V',voltage_scale_to_DUT:1,divider_id:'',digitizer_id:'',channel_id:'',measurement_plane:'',baseline_V:0,beginning_s:0,polarity:q.polarity,calibration_reference:''},provenance:{evidence_kind:document.getElementById('evidence-kind')?.value??'SYNTHETIC_TEST',note:'Replace every example/blank with actual shot and measurement-chain metadata. Suggested settings are not proof of actual settings.'}};const url=URL.createObjectURL(new Blob([JSON.stringify(template,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='measurement_metadata_template.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function showMeasurement(){const el=document.getElementById('measurement-result');if(el&&state.measurement)renderImported(el,{measurement:state.measurement,drawWaveform});}
async function savedMeasurements(){if(!state.bundle?.result)return;const token=renderToken,runId=state.bundle.run.run_id,rows=await api(`/api/runs/${runId}/measurements`);if(token!==renderToken||runId!==state.bundle?.run?.run_id)return;const el=document.getElementById('saved-measurements');if(el)el.innerHTML=rows.length?`<section class="card"><div class="card-head"><h3>Archived measurements for this run</h3></div><div class="actions">${rows.map(r=>`<button class="btn sm" data-shot="${esc(r.measurement_id)}">${view.icon('flask',13)} ${esc(r.shot_id)}</button>`).join('')}</div></section>`:'';}

/* ------------------------------------------------------------------ global events */
document.addEventListener('click',async event=>{const el=event.target.closest('button,a[data-action],[data-candidate]');if(!el||el.disabled)return;try{
  if(el.dataset.nav==='run'){navigate(state.lastRunScreen);return;}
  if(el.dataset.screen){navigate(el.dataset.screen);return;}
  if(el.dataset.shot){const token=renderToken,rid=state.bundle.run.run_id;const measurement=await api(`/api/runs/${rid}/measurement/${el.dataset.shot}`);if(token!==renderToken||rid!==state.bundle?.run?.run_id)return;state.measurement={...measurement,measurement_id:el.dataset.shot};await showMeasurement();return;}
  if(el.dataset.demo){close();await openDemo(el.dataset.demo);return;}
  if(el.dataset.openRun){await openRun(el.dataset.openRun);return;}
  if(el.dataset.compareRun){await compareRun(el.dataset.compareRun);return;}
  if(el.dataset.challenger){state.compareId=el.dataset.challenger;render();return;}
  if(el.dataset.candidate){selectRow(el.dataset.candidate);state.range='tail';navigate('result');return;}
  if(el.dataset.range){state.range=el.dataset.range;render();return;}
  const action=el.dataset.action;if(!action)return;
  if([...RUN_SCREENS,'plan','history','measured','discovery'].includes(action)){navigate(action);return;}
  if(action==='close')close();if(action==='demos')demos();if(action==='boundaries')boundaries();if(action==='export')exports();if(action==='run')await startRun();if(action==='measurement-template')measurementTemplate();
  if(action==='edit'){state.draft=structuredClone(state.bundle.result?.request??state.bundle.run.request);state.annotations=structuredClone(state.bundle.run.annotations??{});navigate('plan');}
}catch(error){toast(error.message,'error');}});
document.addEventListener('keydown',e=>{const t=e.target;if((e.key==='Enter'||e.key===' ')&&t instanceof SVGElement&&t.dataset?.candidate){e.preventDefault();selectRow(t.dataset.candidate);navigate('result');}});
document.getElementById('show-boundaries').addEventListener('click',boundaries);document.getElementById('export-button').addEventListener('click',exports);
const expert=document.getElementById('expert-toggle');try{expert.checked=localStorage.getItem('powernext-expert')==='1';}catch{}document.body.classList.toggle('expert',expert.checked);expert.addEventListener('change',()=>{document.body.classList.toggle('expert',expert.checked);try{localStorage.setItem('powernext-expert',expert.checked?'1':'0');}catch{}});
window.addEventListener('hashchange',()=>{const screen=location.hash.slice(1);if(screen&&screen!==state.screen){preserveDraft();state.screen=screen;if(RUN_SCREENS.includes(screen))state.lastRunScreen=screen;render();}});
modal.addEventListener('click',event=>{if(event.target===modal)close();});

async function initialize(){try{state.meta=await api('/api/meta');state.draft=structuredClone(state.meta.default_request);document.getElementById('footer-version').textContent=`Application ${state.meta.application_version} · interface ${UI_VERSION} · profile ${state.meta.profile.profile_id} · stack ${state.meta.stack_sha256.slice(0,12)}`;
  let stored=null;try{stored=localStorage.getItem('powernext-run');}catch{}if(stored){const token=state.selectionGeneration;try{const restored=await api(`/api/runs/${stored}`);if(token===state.selectionGeneration){state.bundle=restored;state.row=primaryRow(restored.result);}}catch{try{localStorage.removeItem('powernext-run');}catch{}}}
  state.screen=location.hash.slice(1)||'plan';if(RUN_SCREENS.includes(state.screen))state.lastRunScreen=state.screen;await render();if(state.bundle&&['QUEUED','RUNNING'].includes(state.bundle.run.status))pollRun(state.bundle.run.run_id);}
  catch(error){main.innerHTML=`<section class="verdict fail"><div class="verdict-ic">${view.icon('warn',24)}</div><div class="verdict-body"><div class="eyebrow">Local service</div><h1>Local service unavailable</h1><p>${esc(error.message)}</p><p>Start the application launcher, then reload this page.</p></div></section>`;}}
initialize();
