import {esc,fmt,json,reasonList} from './format.js';

export function renderImported(container,{measurement,drawWaveform}){
  const r=measurement.record,m=r.metadata,d=r.clean_trace_diagnostics??{},p=r.predicted_comparison??{},mode=m.configuration.impulse_type,fk=mode==='LI'?'T1_s':'Tp_s';
  const label={CPRI_MEASURED_CLAIMED:'Declared CPRI export',BENCH_MEASURED_UNVERIFIED:'Bench experiment',SYNTHETIC_IMPORT:'Synthetic trace'}[r.evidence_domain]??r.evidence_domain;
  const keys=['crest_magnitude_V',fk,'T2_s'];const vScale=Math.abs(d.metrics?.crest_magnitude_V??0)<1000?1:1000,vUnit=vScale===1?'V':'kV';
  container.innerHTML=`<section class="card measured"><div class="card-head"><h3>Imported trace analysis</h3><span class="chip neutral">${esc(label)}</span></div><p>Shot ${esc(m.shot_id)} · source ${esc(m.source_organization)} · ${esc(m.acquisition_time_utc)}</p><p class="micro">Imported waveform diagnostics · source metadata retained.</p>${r.measurement_quality?.flags?.length?`<div class="quality-flags"><h4>Acquisition checks</h4><ul>${r.measurement_quality.flags.map(f=>`<li><b>${esc(f.code.replaceAll('_',' '))}</b> — ${esc(f.detail)}</li>`).join('')}</ul></div>`:''}<div class="table-wrap"><table class="data"><thead><tr><th>Parameter</th><th>Clean-trace diagnostic</th><th>Matching model prediction</th><th>Diagnostic − prediction</th></tr></thead><tbody>${keys.map(k=>{const scale=k==='crest_magnitude_V'?vScale:1e-6,unit=k==='crest_magnitude_V'?vUnit:'µs';return `<tr><td>${k==='crest_magnitude_V'?'Crest':k.replace('_s','')} (${unit})</td><td>${fmt(d.metrics?.[k],scale)}</td><td>${fmt(p.metrics?.[k],scale)}</td><td>${fmt(p.diagnostic_minus_prediction?.[k],scale)}</td></tr>`;}).join('')}</tbody></table></div><p class="micro">${esc(d.assumption??'No diagnostic record')} Unsupported/noisy/flat/truncated curves retain unavailable timings.</p>${reasonList(d.reason_codes)}<p>Residual RMS: ${fmt(p.voltage_rmse_V,vScale)} ${vUnit} over ${p.overlap_samples??0} overlapping samples. ${esc(p.alignment??p.reason??'Model comparison unavailable.')}</p><div class="seg sm" aria-label="Imported trace window">${['front','tail','full'].map(x=>`<button type="button" data-import-range="${x}" class="${x==='full'?'active':''}">${x}</button>`).join('')}</div><div id="import-chart" class="chart"></div><div class="legend"><span><i class="ln measured"></i>${esc(label)}</span>${p.waveform?'<span><i class="ln ref"></i>Model prediction for declared settings</span>':''}</div><details><summary>Raw provenance, measurement chain and diagnostic record</summary><p>Raw SHA-256: <code>${esc(r.raw_sha256)}</code></p>${json(r)}</details></section>`;
  const imported={time_s:measurement.time_s,voltage_V:measurement.voltage_V,metrics:{...r.local_evaluation,...d.metrics}};
  const series=[{wave:imported,label,kind:'measured'}];if(p.waveform)series.push({wave:p.waveform,label:'Matching model prediction',kind:'reference'});
  const draw=range=>drawWaveform(container.querySelector('#import-chart'),{series,request:{impulse_type:mode,polarity:m.measurement.polarity},row:null,range,markers:false,constructions:false,height:350});
  container.querySelectorAll('[data-import-range]').forEach(b=>b.addEventListener('click',()=>{container.querySelectorAll('[data-import-range]').forEach(x=>x.classList.toggle('active',x===b));draw(b.dataset.importRange);}));draw('full');
}
