import {esc,fmt,json,reasonList} from './format.js';

export function renderImported(container,{measurement,drawWaveform}){
  const r=measurement.record,m=r.metadata,d=r.clean_trace_diagnostics??{},p=r.predicted_comparison??{},mode=m.configuration.impulse_type,fk=mode==='LI'?'T1_s':'Tp_s';
  const label={CPRI_MEASURED_CLAIMED:'CPRI export · user claim, unauthenticated',BENCH_MEASURED_UNVERIFIED:'Bench experiment · unverified',SYNTHETIC_IMPORT:'Synthetic test · not a measurement'}[r.evidence_domain]??r.evidence_domain;
  const keys=['crest_magnitude_V',fk,'T2_s'];
  container.innerHTML=`<section class="card measured"><div class="card-head"><h3>Imported trace analysis</h3><span class="chip caution">${esc(label)}</span></div><p>Shot ${esc(m.shot_id)} · source ${esc(m.source_organization)} · ${esc(m.acquisition_time_utc)}</p><p class="note caution">Diagnostics are unqualified. Calibration is not fitted, source identity is not authenticated, and this record is ineligible for model training or operational approval.</p><div class="table-wrap"><table class="data"><thead><tr><th>Parameter</th><th>Clean-trace diagnostic</th><th>Matching provisional prediction</th><th>Diagnostic − prediction</th></tr></thead><tbody>${keys.map(k=>{const scale=k==='crest_magnitude_V'?1000:1e-6,unit=k==='crest_magnitude_V'?'kV':'µs';return `<tr><td>${k==='crest_magnitude_V'?'Crest':k.replace('_s','')} (${unit})</td><td>${fmt(d.metrics?.[k],scale)}</td><td>${fmt(p.metrics?.[k],scale)}</td><td>${fmt(p.diagnostic_minus_prediction?.[k],scale)}</td></tr>`;}).join('')}</tbody></table></div><p class="micro">${esc(d.assumption??'No diagnostic record')} Unsupported/noisy/flat/truncated curves retain unavailable timings.</p>${reasonList(d.reason_codes)}<p>Residual RMS: ${fmt(p.voltage_rmse_V,1000)} kV over ${p.overlap_samples??0} overlapping samples. ${esc(p.alignment??p.reason??'Model comparison unavailable.')}</p><div class="seg sm" aria-label="Imported trace window">${['front','tail','full'].map(x=>`<button type="button" data-import-range="${x}" class="${x==='full'?'active':''}">${x}</button>`).join('')}</div><div id="import-chart" class="chart"></div><div class="legend"><span><i class="ln measured"></i>${esc(label)}</span>${p.waveform?'<span><i class="ln ref"></i>Provisional simulation of declared actual settings</span>':''}</div><details><summary>Raw provenance, measurement chain and diagnostic record</summary><p>Raw SHA-256: <code>${esc(r.raw_sha256)}</code></p>${json(r)}</details></section>`;
  const imported={time_s:measurement.time_s,voltage_V:measurement.voltage_V,metrics:{...r.local_evaluation,...d.metrics}};
  const series=[{wave:imported,label,kind:'measured'}];if(p.waveform)series.push({wave:p.waveform,label:'Matching provisional simulation',kind:'reference'});
  const draw=range=>drawWaveform(container.querySelector('#import-chart'),{series,request:{impulse_type:mode,polarity:m.measurement.polarity},row:null,range,markers:false,constructions:false,height:350});
  container.querySelectorAll('[data-import-range]').forEach(b=>b.addEventListener('click',()=>{container.querySelectorAll('[data-import-range]').forEach(x=>x.classList.toggle('active',x===b));draw(b.dataset.importRange);}));draw('full');
}
