// Pure rendering of saved engineering results. Views never rerank, rescore or recompute.
import {changeValue,tailLabel,esc,fmt,fixed,signed,frontKey,frontName,metrics,json,date,reasonList,inputNumber,MV,ohm,paramLabel,paramLong,paramUnit,paramKeys,statusAxes,statusTone,statusText,tierName,reasonNames} from './format.js';
import {toleranceBar,dotRows,scoreBar,searchMatrix,toleranceScatter,funnel} from './charts.js';

const P={check:'M5 12.5l4.5 4.5L19 7.5',cross:'M7 7l10 10M17 7L7 17',dash:'M7 12h10',dot:'M12 12m-3.2 0a3.2 3.2 0 1 0 6.4 0a3.2 3.2 0 1 0-6.4 0',warn:'M12 4l9 16H3zM12 10v4.5M12 17.4v.2',lock:'M7 11V8a5 5 0 0 1 10 0v3M5.5 11h13v9h-13z',arrow:'M5 12h14M13 6l6 6-6 6',back:'M19 12H5M11 6l-6 6 6 6',down:'M12 4v12M6 11l6 6 6-6M5 20h14',wave:'M3 14c2 0 2-8 4-8s2 12 4 12 2-9 4-9 2 5 4 5h2',grid:'M4 4h7v7H4zM13 4h7v7h-7zM4 13h7v7H4zM13 13h7v7h-7z',history:'M4 12a8 8 0 1 0 2.4-5.7M4 4v4h4M12 8v4l3 2',flask:'M9 3h6M10 3v6L4.5 19a1.3 1.3 0 0 0 1.2 2h12.6a1.3 1.3 0 0 0 1.2-2L14 9V3',play:'M8 5l11 7-11 7z',edit:'M4 20h4L19 9l-4-4L4 16zM13.5 6.5l4 4',info:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18zM12 11v6M12 7.5v.2',layers:'M12 3l9 5-9 5-9-5zM3 13l9 5 9-5',compare:'M8 4v16M16 4v16M3 8h5M16 16h5',cpu:'M7 7h10v10H7zM10 3v4M14 3v4M10 17v4M14 17v4M3 10h4M3 14h4M17 10h4M17 14h4',bolt:'M13 3L5 14h6l-1 7 8-11h-6z',search:'M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14zM20 20l-4-4',plus:'M12 5v14M5 12h14',external:'M14 4h6v6M20 4l-9 9M18 14v6H4V6h6',close:'M6 6l12 12M18 6L6 18',sliders:'M4 7h10M18 7h2M4 17h4M12 17h8M14 4v6M8 14v6'};
export const icon=(name,size=16)=>`<svg class="ic" width="${size}" height="${size}" viewBox="0 0 24 24" aria-hidden="true"><path d="${P[name]??P.dot}"/></svg>`;
export const head=(kicker,title,description,actions='')=>`<div class="page-head"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1>${description?`<p>${esc(description)}</p>`:''}</div>${actions?`<div class="actions">${actions}</div>`:''}</div>`;
const button=(label,action,cls='')=>`<button type="button" class="btn ${cls}" data-action="${action}">${label}</button>`;
const options=(list,value)=>list.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`;}).join('');
const chip=(text,tone='neutral',ic=null)=>`<span class="chip ${tone}">${ic?icon(ic,13):''}${esc(text)}</span>`;
const kv=(label,value,cls='')=>`<div class="kv ${cls}"><dt>${esc(label)}</dt><dd>${value}</dd></div>`;
const bestOf=p=>p?.best_configuration??p?.closest_noncompliant??p?.candidates?.[0]??null;

/* ------------------------------------------------------------------ plan */
const provenance=(name,value)=>`<select aria-label="Provenance of ${esc(name.replaceAll('_',' '))}" class="prov" data-provenance="${name}">${options([['assumed','Assumed'],['estimated','Estimated'],['measured','Measured'],['known','Known']],value??'assumed')}</select>`;
function field(id,label,value,unit,source,annotations,{hint='',big=false}={}){return `<div class="field ${big?'big':''}"><div class="field-head"><label for="${id}">${label}</label>${source?provenance(source,annotations?.value_provenance?.[source]):''}</div><div class="input-unit"><input id="${id}" type="number" step="any" min="0" required inputmode="decimal" value="${esc(inputNumber(value))}"><span class="unit">${unit}</span></div>${hint?`<div class="hint">${hint}</div>`:''}</div>`;}

export function targetStrip(profile,mode){const p=profile.waveform_profile[mode],front=mode==='LI'?'T1':'Tp';return `<dl class="spec-line"><div><dt>Target ${mode==='LI'?'T1 / T2':'Tp / T2'}</dt><dd class="num">${fmt(p[front+'_target'].value,1e-6)} / ${fmt(p.T2_target.value,1e-6)} µs</dd></div><div><dt>Crest tolerance</dt><dd class="num">±${fmt(profile.waveform_profile.crest_relative_tolerance.value*100)} %</dd></div><div><dt>${front} tolerance</dt><dd class="num">±${fmt(p[front+'_relative_tolerance'].value*100)} %</dd></div><div><dt>T2 tolerance</dt><dd class="num">±${fmt(p.T2_relative_tolerance.value*100)} %</dd></div><div class="spec-note">${mode==='LI'?'Virtual front time T1':'Competition convention · physical time to peak'}</div></dl>`;}

export function schematic(topology,setup,basic){
  // GSHUNT_v0: Rt across the generator node; OSHUNT_v0: Rt across the output node (Physics CIRCUIT_TOPOLOGY_SPEC §2–3).
  const gen=topology!=='OSHUNT_v0';
  const res=(x,y,vert=false)=>vert?`<path class="sc-r" d="M${x} ${y}v8l-6 3 12 6-12 6 12 6-12 6 6 3v8"/>`:`<path class="sc-r" d="M${x} ${y}h8l3-6 6 12 6-12 6 12 6-12 3 6h8"/>`;
  const cap=(x,y)=>`<path class="sc-w" d="M${x} ${y}v22M${x-14} ${y+22}h28M${x-14} ${y+30}h28M${x} ${y+30}v22"/>`;
  const ind=(x,y)=>`<path class="sc-r" d="M${x} ${y}h6a5 5 0 0 1 10 0a5 5 0 0 1 10 0a5 5 0 0 1 10 0a5 5 0 0 1 10 0h6"/>`;
  const load=`${fmt((setup.dut_capacitance_F+setup.divider_capacitance_F+setup.stray_capacitance_F)*1e12,1,3)} pF${setup.basic_coverage_assumption==='ADDITIONAL_DISJOINT'?` + ${fmt(basic,1e-12,0)}`:''}`;
  return `<svg class="schematic" viewBox="0 0 440 180" role="img" aria-label="Declared equivalent circuit ${esc(topology)}: Marx capacitance Cg, series front resistance Rf, loop inductance L, load capacitance, and tail resistance Rt across the ${gen?'generator':'output'} node">
  <path class="sc-w" d="M40 40H140M186 40H214M266 40H340M40 40v36M40 128v24H${gen?340:396}M340 40v36M340 128v24"/>${cap(40,76)}<text class="sc-t" x="20" y="172">Cg · Marx, N stages</text>
  ${res(140,40)}<text class="sc-t" x="163" y="24" text-anchor="middle">Rf = N·rf</text>${ind(214,40)}<text class="sc-t" x="240" y="24" text-anchor="middle">L ${fmt(setup.loop_inductance_H,1e-6)} µH</text>
  ${gen?`<path class="sc-w" d="M104 40V64M104 110V152"/>${res(104,64,true)}<text class="sc-t" x="114" y="92">Rt = N·rt</text><circle class="sc-node" cx="104" cy="40" r="3"/>`:`<path class="sc-w" d="M340 40H396V64M396 110V152H340"/>${res(396,64,true)}<text class="sc-t" x="406" y="92">Rt</text><text class="sc-s" x="406" y="104">N·rt</text>`}
  ${cap(340,76)}<text class="sc-t" x="${gen?356:326}" y="96" ${gen?'':'text-anchor="end"'}>C load</text><text class="sc-s" x="${gen?356:326}" y="109" ${gen?'':'text-anchor="end"'}>${load} pF</text>
  <circle class="sc-node" cx="340" cy="40" r="3.5"/><text class="sc-s" x="340" y="30" text-anchor="middle">DUT HV</text><path class="sc-w" d="M210 152v8M198 160h24M203 165h14M208 170h4"/></svg>`;
}

export function plan(s){
  const q=s.draft??s.meta.default_request,p=s.meta.profile,setup=q.setup,a=s.annotations??{},c=q.current_setting??{},mode=q.impulse_type;
  const modeCard=(m,title,std)=>`<button type="button" class="mode-card ${mode===m?'active':''}" data-mode="${m}" aria-pressed="${mode===m}"><span class="mode-radio" aria-hidden="true"></span><span class="mode-title">${title} <span class="mode-abbr">${m}</span></span><span class="mode-std num">${std}</span></button>`;
  const wp=p.waveform_profile;
  const section=(title,description)=>`<div class="panel-head"><h2>${title}</h2>${description?`<p>${description}</p>`:''}</div>`;
  return `<div class="plan-hero"><h1>Plan an impulse test</h1><p>Declare the impulse and the fixed test arrangement. Every configuration in the declared catalogue is then evaluated and ranked against the waveform profile.</p></div>
  <div class="plan-layout"><form class="plan-form" id="test-form">
  <section class="panel">${section('Impulse requirement','Waveform, requested output crest and polarity.')}
    <input type="hidden" id="mode" value="${esc(mode)}"><div class="mode-row" role="group" aria-label="Impulse type">${modeCard('LI','Lightning impulse',`${fmt(wp.LI.T1_target.value,1e-6)} / ${fmt(wp.LI.T2_target.value,1e-6)} µs`)}${modeCard('SI','Switching impulse',`${fmt(wp.SI.Tp_target.value,1e-6)} / ${fmt(wp.SI.T2_target.value,1e-6)} µs`)}</div>
    <div class="target-strip" id="target-strip">${targetStrip(p,mode)}</div>
    <div class="crest-row">${field('target','Requested output crest',q.target_crest_V/1000,'kV','target_crest_V',a,{big:true,hint:`<span id="target-mv">${MV(q.target_crest_V)}</span> · profile range ≈ ${fmt(p.limits.requested_output_crest_min_approx.value,1000)} kV – ${fmt(p.limits.requested_output_crest_max_approx.value,1e6,1)} MV, subject to feasibility`})}
    <div class="field"><div class="field-head"><span class="label" id="polarity-label">Polarity</span></div><input type="hidden" id="polarity" value="${esc(String(q.polarity??1))}"><div class="seg" role="group" aria-labelledby="polarity-label"><button type="button" data-polarity="1" class="${(q.polarity??1)===1?'active':''}" aria-pressed="${(q.polarity??1)===1}">+ Positive</button><button type="button" data-polarity="-1" class="${q.polarity===-1?'active':''}" aria-pressed="${q.polarity===-1}">− Negative</button></div></div>
    <div class="field"><div class="field-head"><label for="request-id">Test reference</label></div><input id="request-id" maxlength="100" value="${esc(q.request_id??'LOCAL_TEST')}"></div></div>
  </section>
  <section class="panel">${section('Test object & measuring circuit','Held fixed during the search. The tag beside each value records whether it is known, measured, estimated or assumed.')}
    <div class="fields four">${field('dut','DUT / load capacitance',setup.dut_capacitance_F*1e12,'pF','dut_capacitance_F',a)}${field('divider','Divider capacitance',setup.divider_capacitance_F*1e12,'pF','divider_capacitance_F',a)}${field('stray','Stray capacitance',setup.stray_capacitance_F*1e12,'pF','stray_capacitance_F',a)}${field('inductance','Loop inductance',setup.loop_inductance_H*1e6,'µH','loop_inductance_H',a)}</div>
    <div class="field full"><label for="coverage">Basic load capacitance (${fmt(p.capacitors.basic_load_capacitance.value,1e-12,0)} pF) coverage</label><select id="coverage">${options([['ADDITIONAL_DISJOINT',`Additional — ${fmt(p.capacitors.basic_load_capacitance.value,1e-12,0)} pF is added to the values above`],['INCLUDED_IN_OTHER_COMPONENTS','Included — already part of the capacitances entered above']],setup.basic_coverage_assumption)}</select></div>
  </section>
  <section class="panel">${section('Generator, topology & recipe scope','Versioned equipment profile and declared circuit hypothesis. The optimiser never changes these.')}
    <div class="fields"><div class="field"><label for="profile">Equipment profile</label><select id="profile">${options([p.profile_id],q.equipment_profile_id)}</select></div><div class="field"><label for="topology">Declared topology</label><select id="topology">${options(p.topology.development_topologies.map(t=>[t,`${t} · ${t.startsWith('G')?'tail across generator':'tail across output'}`]),q.topology_id)}</select></div>
    <div class="field"><label for="scope">Recipe scope</label><select id="scope">${options([['development','Declared circuit recipes'],['approved','Approved recipes only']],q.catalog_scope??'development')}</select></div><div class="field"><label for="auxiliary">Auxiliary branches</label><select id="auxiliary"><option value="UNCONFIRMED_AUXILIARY_BRANCHES_OMITTED">Auxiliary branches excluded</option></select></div></div>
  </section>
  <section class="panel">${section('Available components','Only the values ticked here enter the catalogue. Clearing a group means none of those components are available.')}${inventoryControls(q,p)}${recipeControls(q,p)}</section>
  <details class="panel fold"><summary><span>Advanced circuit conditions</span><small>Loop resistance · load leakage · setup ID</small></summary><div class="fields">${field('loop-r','Additional loop resistance',setup.loop_resistance_ohm??0,'Ω','loop_resistance_ohm',a)}<div class="field"><div class="field-head"><label for="load-r">Load leakage resistance</label>${provenance('load_resistance_ohm',a.value_provenance?.load_resistance_ohm)}</div><div class="input-unit"><input id="load-r" type="number" min="0" step="any" value="${setup.load_resistance_ohm?esc(inputNumber(setup.load_resistance_ohm/1e6)):''}" placeholder="Omitted"><span class="unit">MΩ</span></div><div class="hint">Blank uses the supported omitted-leakage scenario.</div></div><div class="field full"><label for="setup-id">Setup ID</label><input id="setup-id" value="${esc(setup.setup_id??'DECLARED_LOCAL_SETUP')}"></div></div></details>
  <details class="panel fold" ${q.current_setting?'open':''}><summary><span>Current generator setting</span><small>Optional · lets the ranking count hardware changes</small></summary><label class="check-row"><input id="use-current" type="checkbox" ${q.current_setting?'checked':''}> Include the setting currently erected on the generator</label><div id="current-fields" ${q.current_setting?'':'hidden'}><div class="fields">${field('current-stages','Active stages',c.stages??'','',null,a)}${field('current-charge','Charge per stage',c.stage_charge_V?c.stage_charge_V/1000:'','kV',null,a)}<div class="field"><label for="current-front">Front resistance / stage</label><select id="current-front">${options(p.resistors.front_per_stage.map(x=>[String(x.value),`${x.value} Ω`]),String(c.front_per_stage_ohm??p.resistors.front_per_stage[0].value))}</select></div><div class="field"><label for="current-tail">Tail resistance / stage</label><div class="input-unit"><input id="current-tail" type="number" min="0" step="any" value="${c.tail_per_stage_ohm??''}"><span class="unit">Ω</span></div></div><div class="field full"><label for="current-recipe">Recipe ID</label><input id="current-recipe" value="${esc(c.recipe_id??'')}"></div></div></div></details>
  <details class="panel fold"><summary><span>Assumptions & operator notes</span><small>Stored with the immutable result</small></summary><div class="fields"><div class="field full"><label for="assumptions">Explicit assumptions (one per line)</label><textarea id="assumptions">${esc((q.assumptions??[]).join('\n'))}</textarea></div><div class="field full"><label for="notes">Operator notes</label><textarea id="notes">${esc(a.notes??'')}</textarea></div></div></details>
  <div id="form-error" role="alert"></div></form>
  <aside class="plan-aside"><section class="card sheet"><div class="card-head"><h3>Test sheet</h3><span class="micro-inline">Draft · not yet run</span></div><div id="test-sheet">${testSheet(q,p)}</div><div class="schematic-wrap" id="schematic">${schematic(q.topology_id,setup,p.capacitors.basic_load_capacitance.value)}</div><p class="micro">Declared equivalent circuit.</p><button class="btn primary block lg" type="submit" form="test-form">Review &amp; run optimisation</button><p class="micro center">Nothing runs until you confirm the fixed setup.</p></section>
  <section class="card"><div class="card-head"><h3>CPRI generator profile</h3><button class="btn link" type="button" data-action="boundaries">Technical details</button></div><dl class="kvs tight">${kv('Stages available',`<span class="num">${p.limits.available_stages_max.value}</span>`)}${kv('Max charge per stage',`<span class="num">${fmt(p.limits.stage_charge_max.value,1000)} kV</span>`)}${kv('Max summed charge',`<span class="num">${fmt(p.limits.summed_stage_charge_max.value,1e6)} MV</span>`)}${kv('Stage capacitance',`<span class="num">${fmt(p.capacitors.stage_impulse_capacitance.value,1e-6)} µF</span>`)}${kv('Rated stored energy',`<span class="num">${fmt(p.limits.stored_energy_total_rated.value,1000)} kJ</span>`)}</dl><h4>Confirmed resistor components (Ω / stage)</h4><dl class="kvs tight comp-list">${kv('Front',`<span class="num">${p.resistors.front_per_stage.map(r=>fmt(r.value)).join(', ')}</span>`)}${kv('LI tail',`<span class="num">${p.resistors.LI_tail_per_stage_confirmed.map(r=>fmt(r.value)).join(', ')}</span>`)}${kv('SI tail',`<span class="num">${p.resistors.SI_tail_per_stage.map(r=>fmt(r.value)).join(', ')}</span>`)}</dl></section>
  <section class="card"><div class="card-head"><h3>Example cases</h3><button class="btn link" type="button" data-action="demos">All ${s.meta.demonstrations.length}</button></div>${s.meta.demonstrations.slice(0,4).map(d=>`<button class="scenario-row" type="button" data-demo="${d.id}"><span><b>${esc(d.title)}</b><small>${esc(d.label)}</small></span><span class="sc-tag ${demoTone(d.tag)}">${esc(d.tag)}</span></button>`).join('')}</section></aside></div>`;
}
export function testSheet(q,p){const s=q.setup,total=(s.dut_capacitance_F??0)+(s.divider_capacitance_F??0)+(s.stray_capacitance_F??0);
  return `<div class="sheet-main"><small>${q.impulse_type==='LI'?'Lightning impulse · 1.2/50 µs':'Switching impulse · 250/2500 µs'}</small><b class="num">${q.polarity===-1?'−':'+'}${fmt(q.target_crest_V,1000,3)} kV</b><small>${MV(q.target_crest_V)} requested crest</small></div><dl class="kvs tight">${kv('DUT · divider · stray',`<span class="num">${fmt(s.dut_capacitance_F,1e-12)} · ${fmt(s.divider_capacitance_F,1e-12)} · ${fmt(s.stray_capacitance_F,1e-12)} pF</span>`)}${kv('Sum of declared C',`<span class="num">${fmt(total,1e-12,3)} pF</span>${s.basic_coverage_assumption==='ADDITIONAL_DISJOINT'?` <small>+ ${fmt(p.capacitors.basic_load_capacitance.value,1e-12,0)} pF basic</small>`:''}`)}${kv('Loop inductance',`<span class="num">${fmt(s.loop_inductance_H,1e-6)} µH</span>`)}${kv('Topology · scope',`${esc(q.topology_id)} · ${esc(q.catalog_scope)}`)}</dl>${inventorySummary(q)}`;}


export function inventorySummary(q){const values=key=>Object.hasOwn(q,key)?(q[key].length?q[key].map(v=>`${fmt(v)} Ω`).join(', '):'None available'):'All confirmed values';return `<dl class="kvs tight" data-inventory-summary>${kv('Available front components',values('available_front_per_stage_ohm'))}${kv('Available tail components',values('available_tail_per_stage_ohm'))}</dl>`;}
export function inventoryControls(q,p){
  const group=(kind,label,values,key)=>`<fieldset class="toggle-group"><legend>${label} <span>Ω per stage</span></legend><div class="toggles">${values.map(({value})=>`<label class="toggle"><input type="checkbox" data-inventory="${kind}" value="${value}" ${!Object.hasOwn(q,key)||q[key].includes(value)?'checked':''}><span class="num">${fmt(value)}</span></label>`).join('')}</div></fieldset>`;
  return `<div id="inventory-controls" data-resistor-inventory><div class="inventory-grid">${group('front','Front resistors',p.resistors.front_per_stage,'available_front_per_stage_ohm')}${group('tail',`${q.impulse_type} tail resistors`,q.impulse_type==='LI'?p.resistors.LI_tail_per_stage_confirmed:p.resistors.SI_tail_per_stage,'available_tail_per_stage_ohm')}</div></div>`;
}

/* ------------------------------------------------------------------ shared run frame */
const RUN_TABS=[['result','Recommendation','bolt'],['alternatives','Compare','compare'],['waveform','Waveform','wave'],['evidence','Physics + ML','cpu'],['search','Complete search','grid'],['screening','ML scenarios','cpu']];
export function runFrame(s){
  const b=s.bundle,p=b?.result,q=p?.request??b?.run?.request,run=b?.run;if(!q)return '';
  const src=run?.source==='SYNTHETIC_DEMO'?chip('Saved simulation','info','layers'):run?.source==='REOPENED_EVIDENCE'?chip('Reopened evidence','neutral'):chip(run?.status==='COMPLETED'?'Computed locally':run?.status??'','neutral');
  const outcome=p?(p.no_solution?chip('No compliant configuration','fail','cross'):chip('Numerically compliant setting found','pass','check')):'';
  const inv=key=>Object.hasOwn(q,key)?(q[key].length?q[key].map(v=>fmt(v)).join(', ')+' Ω':'none'):'all confirmed';
  const fact=(label,value)=>`<div><dt>${label}</dt><dd class="num">${value}</dd></div>`;
  return `<div class="run-bar"><div class="run-id"><div class="run-title"><b>${esc(q.request_id)}</b><span class="run-mode">${esc(q.impulse_type)}</span></div><dl class="run-facts">${fact('Crest',`${q.polarity===-1?'−':'+'}${fmt(q.target_crest_V,1000)} kV`)}${fact('DUT',`${fmt(q.setup.dut_capacitance_F,1e-12)} pF`)}${fact('Loop L',`${fmt(q.setup.loop_inductance_H,1e-6)} µH`)}${fact('Topology',esc(q.topology_id))}${fact('Scope',esc(q.catalog_scope))}${fact('Front parts',inv('available_front_per_stage_ohm'))}${fact('Tail parts',inv('available_tail_per_stage_ohm'))}</dl></div><div class="run-flags">${outcome}${src}<span class="run-date">${date(run?.created_at)}</span>${button(`${icon('edit',14)} Edit request`,'edit','ghost sm')}</div></div>
  ${b?.result&&b.artifact_compatibility!=='MATCHES_CURRENT_STACK'?'<div class="note caution" data-historical-status>Historical result — recorded Physics, ML and Optimizer identities are preserved. This is not a new validation under the current release.</div>':''}
  <nav class="subnav" aria-label="Result views">${[...RUN_TABS.filter(x=>x[0]!=='screening'),['adjustment','Next adjustment','arrow']].map(([k,l,i])=>`<button type="button" data-screen="${k}" class="${s.screen===k?'active':''}" ${s.screen===k?'aria-current="page"':''}>${icon(i,15)}${l}${k==='search'&&p?`<span class="count">${p.search.evaluated_count}</span>`:''}</button>`).join('')}</nav>`;
}

/* ------------------------------------------------------------------ status axes */
export function axes(row){return `<div class="axes" role="list" aria-label="Numerical result, model support and waveform validity">${statusAxes(row).slice(0,3).map(a=>`<div class="axis ${a.tone}" role="listitem"><div class="axis-label">${a.label}</div><div class="axis-value"><span class="axis-ic">${icon(a.icon,14)}</span>${esc(a.value)}</div><div class="axis-note">${esc(a.note)}</div><code class="axis-code">${esc(a.code)}</code></div>`).join('')}</div>`;}

export function metricsBlock(row,p){const m=metrics(row),keys=['crest',frontKey(p),'T2_s'],values=[m.crest_magnitude_V,m[frontKey(p)],m.T2_s];return `<div class="metrics">${[paramLong('crest'),`${frontName(p)} · ${p.request.impulse_type==='LI'?'front time':'time to peak'}`,'T2 · time to half'].map((label,i)=>{const part=row.score?.components?.[keys[i]];return `<div class="metric"><small>${label}</small><strong class="num" data-metric="${keys[i]}">${fmt(values[i],i?1e-6:1000)}<span class="unit-s">${i?'µs':'kV'}</span></strong><div class="delta ${part&&!part.within_limits?'out':''}">${part?`${signed(part.deviation_pct)}% from target${part.within_limits?'':' · outside limit'}`:'Not evaluable'}</div></div>`;}).join('')}</div>`;}

export function scoreTerms(row,p){return p?scoreBar(row,p):Object.entries(row.score?.components??{}).map(([k,c])=>`<div class="kv"><dt>${paramLabel(k)}</dt><dd class="num">${fmt(c.squared_contribution,1,6)}</dd></div>`).join('');}

export function candidateTable(rows,p,{expert=false,selected=null}={}){const fk=frontKey(p);return `<div class="table-wrap"><table class="data"><thead><tr><th>Rank</th><th>Setting</th><th class="r">Front / tail Ω</th><th class="r">Crest kV</th><th class="r">${frontName(p)} µs</th><th class="r">T2 µs</th><th>Numerical</th><th class="r">Score J</th>${expert?`<th class="r">e crest / ${frontName(p)} / T2</th><th>Tier · first failing reason</th>`:''}<th>Model</th><th>Recipe</th></tr></thead><tbody>${rows.map(r=>{const c=r.configuration,m=metrics(r),st=r.assessment.compliance_status,pr=r.prediction??{};return `<tr data-candidate-row="${r.candidate_id}" class="${r.candidate_id===selected?'selected':''}"><td><button type="button" class="rank-btn ${r.rank===1?'first':''}" data-candidate="${r.candidate_id}" aria-label="Inspect configuration rank ${r.rank}">#${r.rank}</button></td><td><b class="num">${c.stages}</b> stages <span class="num muted">× ${fmt(c.stage_charge_V,1000)} kV</span><span class="cid">${esc(r.candidate_id)}</span></td><td class="r num">${fmt(c.front_per_stage_ohm)} / ${tailLabel(c)}</td><td class="r num ${r.score?.components?.crest&&!r.score.components.crest.within_limits?'out-text':''}" data-raw-value="${m.crest_magnitude_V??''}">${fmt(m.crest_magnitude_V,1000)}</td><td class="r num ${r.score?.components?.[fk]&&!r.score.components[fk].within_limits?'out-text':''}" data-raw-value="${m[fk]??''}">${fmt(m[fk],1e-6)}</td><td class="r num ${r.score?.components?.T2_s&&!r.score.components.T2_s.within_limits?'out-text':''}" data-raw-value="${m.T2_s??''}">${fmt(m.T2_s,1e-6)}</td><td>${chip(statusText(st),statusTone(st),st==='PASS'?'check':st==='FAIL'?'cross':'dash')}</td><td class="r num">${fmt(r.score?.J,1,6)}</td>${expert?`<td class="r num small">${Object.values(r.score?.components??{}).map(x=>signed(x.normalized_deviation,3)).join(' / ')||'Not scored'}</td><td class="wrap small">${esc(tierName(r))}${r.reason_codes.filter(x=>x.startsWith('OUTSIDE_')||x.includes('UNSUPPORTED')||x.includes('OSCILLATORY')||x.includes('CREST_BAND')).length?` · ${esc(r.reason_codes.filter(x=>x.startsWith('OUTSIDE_')||x.includes('UNSUPPORTED')||x.includes('OSCILLATORY')||x.includes('CREST_BAND')).map(x=>reasonNames[x]??x).join('; '))}`:''}</td>`:''}<td class="small">${pr.status==='ML_WITH_PHYSICS_VERIFICATION'?'ML + reference':pr.status==='PHYSICS_FALLBACK'?'Physics fallback':esc((pr.status??'—').replaceAll('_',' ').toLowerCase())}</td><td>${chip('Declared circuit','neutral')}</td></tr>`;}).join('')}</tbody></table></div>`;}

/* ------------------------------------------------------------------ recommendation */
function utilisation(row){
  const want=[['active_stages','Active stages',v=>fmt(v),1],['stage_charge_V','Charge per stage',v=>`${fmt(v,1000)} kV`,1000],['summed_charge_V','Summed charge',v=>`${fmt(v,1e6,3)} MV`,1],['total_energy_J','Stored energy',v=>`${fmt(v,1000)} kJ`,1]];
  return `<div class="util">${want.map(([key,label,f])=>{const c=row.hard_constraints.constraints.find(x=>x.constraint===key);if(!c)return '';const limit=Array.isArray(c.limit)?c.limit[1]:c.limit,frac=Number.isFinite(limit)&&limit?c.value/limit:null,at=frac!==null&&frac>=1-1e-12;return `<div class="util-row ${at?'binding':''}"><span>${label}</span><div class="util-track"><span style="width:${Math.min(100,(frac??0)*100)}%"></span></div><span class="num">${f(c.value)} <small>/ ${f(limit)}</small></span>${at?chip('At limit','caution'):''}</div>`;}).join('')}</div>`;
}
function settingCard(row,p,label,tone){const c=row.configuration;return `<section class="card setting ${tone}"><div class="card-head"><span class="kicker">${label}</span>${chip(`Rank #${row.rank} of ${p.search.evaluated_count}`,'neutral')}</div>
  <div class="setting-hero"><div class="big-stat"><span class="big-num num">${c.stages}</span><span class="big-label">active stages<small>of ${row.hard_constraints.constraints.find(x=>x.constraint==='active_stages')?.limit?.[1]??15} available</small></span></div><div class="big-stat right"><span class="big-num num" data-raw-charge="${c.stage_charge_V}">${fixed(c.stage_charge_V,1000,3)}</span><span class="big-label">kV per stage<small>charging voltage</small></span></div></div>
  <div class="resistors"><div><small>Front resistor</small><b class="num">${fmt(c.front_per_stage_ohm)} Ω <span>/ stage</span></b><span class="num muted">${ohm(row.front_recipe?.assumed_total_ohm)} total (N·rf, assumed)</span></div><div><small>Tail resistor</small><b class="num">${tailLabel(c)} Ω <span>/ stage</span></b><span class="num muted">${ohm(row.tail_recipe?.assumed_total_ohm)} total (N·rt, assumed)</span></div></div>
  ${utilisation(row)}
  ${componentBill(row)}<div class="recipe"><span>Recipe <code>${esc(c.recipe_id)}</code> · ${c.polarity===-1?'negative':'positive'} polarity</span></div></section>`;}

function conformityCard(row,p){const keys=paramKeys(p);return `<section class="card"><div class="card-head"><h3>Waveform conformity</h3>${chip(row.assessment.compliance_status==='PASS'?'All inside limits':row.assessment.compliance_status==='FAIL'?'Outside limits':'Not evaluable',statusTone(row.assessment.compliance_status))}</div><p class="card-sub">Saved reference waveform against the unchanged tolerance interval. Shaded = allowed, tick = target.</p>${keys.map(k=>toleranceBar(k,row.score?.components?.[k],{label:paramLong(k)})).join('')}<div class="divider"></div><div class="card-head tight"><h4>Normalised conformity score J</h4><span class="num muted">lower is closer</span></div>${scoreBar(row,p)}<p class="micro">J = Σ (deviation ÷ allowed half-width)². Compliance is checked per parameter first; a small J never overrides a failed limit.</p></section>`;}

export function resultView(s){
  const p=s.bundle.result,row=s.row,best=p.best_configuration,isBest=row&&row.candidate_id===best?.candidate_id,isClosest=row&&row.candidate_id===p.closest_noncompliant?.candidate_id;
  const q=p.request,search=p.search??{};let html='';
  const searchFacts=`<dl class="summary-search">${[['Evaluated',search.evaluated_count],['Evaluable',search.evaluable_count],['Compliant',search.numeric_pass_count]].map(([l,v])=>`<div><dt>${l}</dt><dd class="num">${v??0}</dd></div>`).join('')}</dl>`;
  if(p.no_solution){
    html+=`<section class="summary fail"><div class="summary-main"><div class="summary-top"><span class="kicker">Outcome · exhaustive search of ${search.evaluated_count??0} configurations</span><span class="status-text fail">${icon('cross',14)}No compliant setting</span></div><h1>No compliant configuration found</h1><p><b>No compliant configuration found in the declared catalog.</b> ${p.closest_noncompliant?'The closest evaluated setting is shown with its exact failures. It is not a recommendation.':'No configuration can be selected within this request’s declared inventory and scope.'}</p><p class="scope">${esc(p.no_solution.scope)}</p></div><div class="summary-side">${searchFacts}</div></section>`;
  }else if(row){
    const c=best.configuration,bm=metrics(best),comps=best.score?.components??{};
    const metric=(key,label,value,scale,unit)=>{const d=comps[key];return `<div><dt>${label}</dt><dd><b class="num">${fmt(value,scale)}</b> <small>${unit}</small><span class="dev num ${d&&!d.within_limits?'out-text':''}">${d?`${signed(d.deviation_pct,1)} %`:'—'}</span></dd></div>`;};
    html+=`<section class="summary pass"><div class="summary-main"><div class="summary-top"><span class="kicker">Recommended numerical setting</span><span class="status-text pass">${icon('check',14)}Numerically compliant</span></div><h1><span class="num">${c.stages}</span> stages at <span class="num">${fixed(c.stage_charge_V,1000,3)}</span> kV per stage</h1><p>Front <b class="num">${fmt(c.front_per_stage_ohm)} Ω</b> and tail <b class="num">${tailLabel(c)} Ω</b> per stage <span class="sep">·</span> rank <span class="num">1</span> of <span class="num">${search.evaluated_count}</span> <span class="sep">·</span> Model prediction <span class="sep">·</span> Declared circuit</p></div><div class="summary-side"><dl class="summary-metrics">${metric('crest','Crest',bm.crest_magnitude_V,1000,'kV')}${metric(frontKey(p),frontName(p),bm[frontKey(p)],1e-6,'µs')}${metric('T2_s','T2',bm.T2_s,1e-6,'µs')}</dl>${searchFacts}</div></section>`;
  }
  if(!row)return html+`<section class="card gap-card"><div class="card-head"><h3>Why no setting is available</h3>${chip('Information gap','caution','warn')}</div>${reasonList(p.no_solution?.categories??p.reason_codes)}<p class="note caution">${p.request.catalog_scope==='approved'?'The approved-only catalog is empty because circuit recipes await CPRI confirmation.':'The declared component availability or selected recipe set produces an empty catalog. Review available components and selected arrangements.'}</p><div class="actions">${button('Edit request','edit')}${button('Open scenarios','demos','ghost')}</div></section>`;
  if(!isBest&&!isClosest)html+=`<div class="inspect-banner">${icon('info',16)}<span>Inspecting <b>#${row.rank}</b> — ${esc(tierName(row).toLowerCase())}. ${p.no_solution?'There is no recommendation for this request.':'This is an alternative, not the recommendation.'}</span><button type="button" class="btn sm" data-candidate="${esc((best??p.closest_noncompliant).candidate_id)}">${icon('back',14)} Back to ${p.no_solution?'closest':'#1'}</button></div>`;
  html+=`<details class="status-details"><summary>Technical result details</summary>${axes(row)}</details>`;
  const label=isBest?'Recommended configuration':isClosest&&p.no_solution?'Closest evaluated · NOT a recommendation':`Inspected alternative · rank #${row.rank}`;
  if(p.no_solution)html+=failurePanel(row,p);
  html+=`<div class="grid-2">${settingCard(row,p,label,p.no_solution?'closest':isBest?'best':'')}<section class="card"><div class="card-head"><h3>Reference waveform</h3><button type="button" class="btn ghost sm" data-screen="waveform">Analyse ${icon('arrow',14)}</button></div><div id="result-wave" class="chart">${loading()}</div><div class="legend"><span><i class="ln ref"></i>Saved RLC reference</span><span><i class="ln target"></i>Mathematical nominal target</span><span><i class="ln band"></i>Allowed crest band</span><span><i class="ln mk"></i>Evaluator markers</span></div></section></div>`;
  html+=`<div class="grid-2">${conformityCard(row,p)}<section class="card"><div class="card-head"><h3>${isBest?'Why this setting ranks first':p.no_solution?'Why this is the closest':`Why #${row.rank} sits here`}</h3></div><div id="why-rank">${whyIntro(row,p)}</div><div class="divider"></div><h4>Search funnel</h4>${funnel(p,p.candidates)}<div class="actions">${button(`Compare alternatives ${icon('arrow',14)}`,'alternatives','primary sm')}${button('Physics + ML evidence','evidence','ghost sm')}</div></section></div>`;
  if(row.reason_codes.includes('ML_REFERENCE_COMPLIANCE_DISAGREEMENT'))html+=`<div class="note caution">${icon('warn',15)}<span><b>Physics and ML disagree on compliance for this setting.</b> The saved reference waveform is ${statusText(row.assessment.compliance_status).toLowerCase()}; the ML scalar limits ${row.ml_score?.scalar_limits_pass?'pass':'fail'}. The reference decides; both values stay visible in Physics + ML.</span><button type="button" class="btn sm" data-screen="evidence">Inspect</button></div>`;
  html+=`<div class="grid-2"><details class="card fold-card"><summary><h3>Charging decision & hard limits</h3><small>Exact-target charge, legal interval, every declared constraint</small></summary>${chargeSummary(row)}${constraintTable(row)}</details><details class="card fold-card"><summary><h3>Calculation details & reason codes</h3><small>${row.reason_codes.length} recorded codes</small></summary><h4>Changes from current setup</h4>${row.changes_from_current?row.changes_from_current.length?`<dl class="kvs">${row.changes_from_current.map(x=>kv(x.field.replaceAll('_',' '),`<span class="num">${changeValue(x.field,x.before)} → ${changeValue(x.field,x.after)}</span>`)).join('')}</dl>`:'<p class="muted small">No setting fields change.</p>':'<p class="muted small">No current generator setting was supplied; no change cost is assumed.</p>'}<h4>Reason codes</h4>${reasonList(row.reason_codes.filter(c=>!['TOPOLOGY_UNCONFIRMED','RECIPE_UNCONFIRMED','HARDWARE_NOT_VERIFIED','BASIC_CAPACITANCE_COVERAGE_ASSUMED','AUXILIARY_BRANCH_STATE_UNCONFIRMED'].includes(c)))}<div class="expert-only">${json(row.assumptions)}${json(row.warnings)}</div></details></div>`;
  return html;
}
export function whyIntro(row,p){
  const fk=frontKey(p),comps=row.score?.components;
  if(row.rank===1&&row.assessment.compliance_status==='PASS')return `<p class="lead">It passes every numerical check and has the lowest conformity score J among the <b>${p.search.numeric_pass_count}</b> compliant settings — its reference waveform is the closest to ${p.request.impulse_type==='LI'?'1.2/50 µs':'250/2500 µs'}.</p><div id="why-compare" class="why-compare">${loading()}</div>`;
  if(p.no_solution&&comps){const fails=Object.entries(comps).filter(([,c])=>!c.within_limits).map(([k])=>paramLabel(k));return `<p class="lead">No setting passes. Among evaluable settings this one has the lowest J, so it is the nearest miss — but it still fails <b>${esc(fails.join(', '))}</b>.</p><p class="small muted">${esc(row.ranking_reason)}</p>`;}
  return `<p class="lead">${esc(tierName(row))}. ${esc(row.ranking_reason)}</p>${comps?'':'<p class="small muted">Waveform metrics could not be qualified, so this configuration is not scored.</p>'}${fk?'':''}`;
}
function chargeSummary(row){const q=row.charge_solution;return `<dl class="kvs">${kv('Exact-target charge / stage',`<span class="num">${fmt(q.exact_stage_charge_V,1000)} kV</span>`)}${kv('Selected charge / stage',`<span class="num">${fmt(row.configuration.stage_charge_V,1000)} kV</span>`)}${kv('Crest-band charge interval',`<span class="num">${(q.crest_band_stage_charge_V??[]).map(v=>fmt(v,1000)).join(' – ')} kV</span>`)}${kv('Legal upper limit',`<span class="num">${fmt(row.charge_policy.maximum_V,1000)} kV</span>`)}${kv('Crest band reachable',q.band_feasible?'Yes':'<b class="out-text">No</b>')}${kv('Reliable minimum · resolution',`${q.minimum_reliable_charge_known?'Known':'Unknown'} · ${q.increment_known?'Known':'Unknown'}`)}${kv('Selection method',`<code>${esc(q.selection_method)}</code>`)}</dl>${q.exact_target_within_continuous_limits===false?'<p class="note caution">The exact target is outside the legal charging interval. The legal limit is still checked against the full crest tolerance band.</p>':''}`;}
const CONSTRAINTS={active_stages:['Active stages',v=>fmt(v)],stage_charge_V:['Charge per stage',v=>`${fmt(v,1000,3)} kV`],summed_charge_V:['Summed charge',v=>`${fmt(v,1e6,3)} MV`],stage_energy_J:['Energy per stage',v=>`${fmt(v,1000,3)} kJ`],total_energy_J:['Total stored energy',v=>`${fmt(v,1000,3)} kJ`],shared_configuration_validation:['Shared configuration validation',v=>String(v)],minimum_reliable_charge:['Minimum reliable charge',v=>`${fmt(v,1000,3)} kV`],charge_increment:['Charge increment',v=>`${fmt(v,1000,3)} kV`],component_placements_and_pulse_ratings:['Component placement & pulse ratings',v=>String(v)]};
const cName=k=>CONSTRAINTS[k]?.[0]??k.replaceAll('_',' ');
const cVal=(k,v)=>v===null||v===undefined?'Unknown':typeof v==='number'&&CONSTRAINTS[k]?CONSTRAINTS[k][1](v):typeof v==='number'?fmt(v,1,3):String(v);
export function constraintTable(row){return `<div class="table-wrap"><table class="data compact"><thead><tr><th>Declared constraint</th><th class="r">Value</th><th class="r">Limit</th><th>Status</th></tr></thead><tbody>${row.hard_constraints.constraints.map(x=>{const at=typeof x.value==='number'&&typeof x.limit==='number'&&x.value>=x.limit;return `<tr><td>${esc(cName(x.constraint))}</td><td class="r num">${esc(cVal(x.constraint,x.value))}</td><td class="r num">${esc(Array.isArray(x.limit)?x.limit.map(v=>cVal(x.constraint,v)).join(' – '):x.limit===null?'Unknown':cVal(x.constraint,x.limit))}</td><td>${chip(x.status==='PASS'&&at?'Pass · at limit':x.status,x.status==='FAIL'?'fail':x.status==='UNKNOWN'?'caution':'neutral')}</td></tr>`;}).join('')}</tbody></table></div>`;}

const DIAG=[
  ['physical','Charge & energy limits','Some catalogue settings cannot reach the crest band inside the declared charge/energy limits.',(p,r)=>p.no_solution.categories.includes('DECLARED_CHARGE_LIMIT_INFEASIBILITY_FOR_SOME_CANDIDATES')||r?.reason_codes.includes('CREST_BAND_UNREACHABLE_WITH_CHARGE_LIMITS')],
  ['timing','Waveform conformity in this catalogue','No evaluated configuration meets every required crest and timing band together.',p=>p.no_solution.categories.includes('WAVEFORM_NONCOMPLIANCE_IN_DECLARED_CATALOG')],
  ['domain','Model domain','The trained model was outside its support; Physics fallback supplied every value.',(p,r)=>r?.prediction?.reason_codes?.includes('OUTSIDE_TRAINING_SUPPORT')||p.candidates.some(x=>x.prediction?.reason_codes?.includes('OUTSIDE_TRAINING_SUPPORT'))],
  ['evaluation','Waveform evaluation','Some waveforms could not be qualified by the current evaluator and are not scored.',p=>p.no_solution.categories.includes('MODEL_OR_WAVEFORM_EVALUATION_LIMITATION')],
];
export function failurePanel(row,p){
  const comps=row.score?.components??{},failing=Object.entries(comps).filter(([,v])=>!v.within_limits);
  const binding=row.hard_constraints.constraints.filter(x=>typeof x.value==='number'&&typeof x.limit==='number'&&x.value>=x.limit);
  return `<section class="card failure"><div class="card-head"><h3>What prevents a compliant result</h3>${chip(`${failing.length} parameter${failing.length===1?'':'s'} outside limits`,'fail','cross')}</div>
  <div class="grid-2 inner"><div><h4>Closest setting vs. allowed interval</h4>${failing.length?failing.map(([k,c])=>toleranceBar(k,c,{label:paramLong(k)})).join(''):'<p class="muted small">Not scored.</p>'}<div class="table-wrap"><table class="data compact"><thead><tr><th>Parameter</th><th class="r">Reference</th><th class="r">Allowed interval</th><th class="r">Distance outside interval</th></tr></thead><tbody>${failing.map(([k,v])=>{const [unit,scale]=paramUnit(k),d=Math.max(v.limits[0]-v.value,v.value-v.limits[1],0);return `<tr><td>${paramLabel(k)}</td><td class="r num">${fmt(v.value,scale)} ${unit}</td><td class="r num">${v.limits.map(x=>fmt(x,scale)).join(' – ')} ${unit}</td><td class="r num out-text">${fmt(d,scale)} ${unit}</td></tr>`;}).join('')}</tbody></table></div>${binding.length?`<h4>Binding hardware limits</h4><ul class="bullets">${binding.map(x=>`<li><b>${esc(cName(x.constraint))}</b> is at its declared limit (<span class="num">${esc(cVal(x.constraint,x.value))} of ${esc(cVal(x.constraint,x.limit))}</span>)</li>`).join('')}</ul>`:''}</div>
  <div><h4>Diagnosis by limitation type</h4><div class="diag">${DIAG.map(([k,t,d,test])=>{const on=!!test(p,row);return `<div class="diag-item ${on?'on':''}"><span class="diag-mark">${icon(on?'warn':'dash',14)}</span><div><b>${t}</b><small>${on?d:'Not indicated for this request.'}</small></div><span class="diag-state">${on?'Contributes':'—'}</span></div>`;}).join('')}</div><p class="micro">Categories come from the optimizer's no-solution record: ${esc(p.no_solution.categories.join(', '))}.</p></div></div></section>`;
}

/* ------------------------------------------------------------------ compare */
export function alternatives(s){
  const p=s.bundle.result,rows=p.candidates;if(!rows.length)return resultView(s);
  const top=rows.slice(0,3),max=Math.max(...top.map(r=>r.score?.J??0),1e-12);
  return head('Compare configurations','Why the leader wins','The optimizer’s original order is shown unchanged. Pick any configuration as the challenger to see the decisive ranking field.',button(`${icon('grid',14)} All ${rows.length} configurations`,'search','ghost'))+
  `<div class="shortlist">${top.map((r,i)=>{const c=r.configuration,st=r.assessment.compliance_status;return `<article class="pick ${i===0?'lead':''} ${r.candidate_id===s.compareId?'challenger':''}"><div class="pick-head"><span class="pick-rank">#${r.rank}</span>${chip(statusText(st),statusTone(st),st==='PASS'?'check':st==='FAIL'?'cross':'dash')}</div><div class="pick-setting"><b class="num">${c.stages}</b><span>stages</span><b class="num">${fmt(c.stage_charge_V,1000)}</b><span>kV / stage</span></div><div class="pick-res num">Front ${fmt(c.front_per_stage_ohm)} Ω · Tail ${tailLabel(c)} Ω</div>${paramKeys(p).map(k=>toleranceBar(k,r.score?.components?.[k],{compact:true})).join('')}<div class="pick-j">${scoreBar(r,p,max)}</div><dl class="kvs tight">${kv('Minimum margin',`<span class="num">${fmt(r.score?.minimum_margin,1,4)}</span>`)}${kv('Stored energy',`<span class="num">${fmt(r.hard_constraints.total_energy_J,1000)} kJ</span>`)}${kv('Model',r.prediction?.status==='ML_WITH_PHYSICS_VERIFICATION'?'ML + reference':'Physics fallback')}${kv('Recipe',chip('Model prediction','neutral'))}</dl><div class="pick-actions">${i?`<button type="button" class="btn sm ${r.candidate_id===s.compareId?'primary':''}" data-challenger="${r.candidate_id}">${r.candidate_id===s.compareId?'Challenger':'Set as challenger'}</button>`:'<span class="micro">Leader</span>'}<button type="button" class="btn ghost sm" data-candidate="${r.candidate_id}">Inspect</button></div></article>`;}).join('')}</div>
  <section class="card"><div class="card-head"><h3>Head to head</h3><label class="inline-select">Challenger <select id="compare-choice" aria-label="Choose comparison candidate">${rows.slice(1).map(r=>`<option value="${r.candidate_id}" ${r.candidate_id===s.compareId?'selected':''}>#${r.rank} · ${r.configuration.stages} stages · ${r.configuration.front_per_stage_ohm}/${tailLabel(r)} Ω · ${statusText(r.assessment.compliance_status)}</option>`).join('')}</select></label></div><div id="pair-comparison">${loading()}</div></section>`;
}
export function whySentence(a,b,p,explanation){
  const w=explanation.preferred_id===b.candidate_id?b:a,l=w===a?b:a,d=explanation.decisive_factor;
  if(!explanation.preferred_id)return `#${a.rank} and #${b.rank} have identical ranking keys.`;
  if(d.startsWith('validity')){const fails=Object.entries(l.score?.components??{}).filter(([,c])=>!c.within_limits).map(([k,c])=>{const [u,sc]=paramUnit(k);return `${paramLabel(k)} ${fmt(c.value,sc)} ${u} (allowed ${c.limits.map(x=>fmt(x,sc)).join('–')})`;});return `<b>#${w.rank} is in a better validity tier.</b> #${w.rank}: ${esc(tierName(w).toLowerCase())}; #${l.rank}: ${esc(tierName(l).toLowerCase())}${fails.length?` — it fails ${esc(fails.join('; '))}`:''}. Compliance is decided before any score.`;}
  if(d.includes('score J')){const keys=paramKeys(p),diffs=keys.map(k=>[k,(l.score.components[k]?.squared_contribution??0)-(w.score.components[k]?.squared_contribution??0)]).sort((x,y)=>Math.abs(y[1])-Math.abs(x[1]));const [k]=diffs[0];return `<b>Both are ${esc(tierName(w).toLowerCase())}; #${w.rank}'s reference waveform is closer to target.</b> J ${fmt(w.score.J,1,6)} vs ${fmt(l.score.J,1,6)}. The largest share of that difference comes from ${paramLabel(k)}: ${signed(w.score.components[k].deviation_pct)}% vs ${signed(l.score.components[k].deviation_pct)}% from target.`;}
  if(d.includes('margin'))return `<b>J ties to 12 decimals;</b> #${w.rank} keeps a larger minimum margin to the nearest limit (${fmt(w.score.minimum_margin,1,6)} vs ${fmt(l.score.minimum_margin,1,6)}).`;
  const val={'changed hardware fields':r=>r.changes_from_current?.filter(x=>x.field!=='stage_charge_V').length??0,'stored energy':r=>`${fmt(r.hard_constraints.total_energy_J,1000)} kJ`,'active stages':r=>r.configuration.stages,'front resistance':r=>`${r.configuration.front_per_stage_ohm} Ω`,'tail resistance':r=>`${tailLabel(r)} Ω`,'stable candidate ID':r=>r.candidate_id}[d];
  return `<b>Tied on every earlier criterion;</b> the decisive field is ${esc(d)}${val?`: ${esc(val(w))} vs ${esc(val(l))}`:''}.`;
}
export function comparison(a,b,p,explanation){
  const fk=frontKey(p),win=explanation.preferred_id,row=(label,f,key)=>`<tr class="${key&&explanation.decisive_factor.includes(key)?'decisive':''}"><td>${label}</td><td class="r num ${win===a.candidate_id?'w':''}">${f(a)}</td><td class="r num ${win===b.candidate_id?'w':''}">${f(b)}</td></tr>`;
  const comp=(k,f)=>r=>r.score?.components?.[k]?f(r.score.components[k]):'—';
  return `<div class="why-banner">${icon('info',18)}<div>${whySentence(a,b,p,explanation)}<small>Decisive field: <b>${esc(explanation.decisive_factor)}</b> · ${esc(explanation.policy)}</small></div></div>
  <div class="grid-2 inner"><div class="table-wrap"><table class="data compact h2h"><thead><tr><th>Field</th><th class="r">#${a.rank}</th><th class="r">#${b.rank}</th></tr></thead><tbody>
  ${row('Numerical compliance',r=>statusText(r.assessment.compliance_status),'validity')}${row('Score J',r=>fmt(r.score?.J,1,6),'score J')}${row('· crest term',comp('crest',c=>fmt(c.squared_contribution,1,6)))}${row(`· ${frontName(p)} term`,comp(fk,c=>fmt(c.squared_contribution,1,6)))}${row('· T2 term',comp('T2_s',c=>fmt(c.squared_contribution,1,6)))}${row('Minimum margin',r=>fmt(r.score?.minimum_margin,1,6),'margin')}${row('Changed hardware fields',r=>r.changes_from_current?String(r.changes_from_current.filter(x=>x.field!=='stage_charge_V').length):'—','changed')}${row('Stored energy',r=>`${fmt(r.hard_constraints.total_energy_J,1000)} kJ`,'energy')}${row('Active stages',r=>String(r.configuration.stages),'stages')}${row('Charge / stage',r=>`${fmt(r.configuration.stage_charge_V,1000)} kV`)}${row('Front / tail per stage',r=>`${r.configuration.front_per_stage_ohm} / ${tailLabel(r)} Ω`,'front')}${row('Crest',comp('crest',c=>`${fmt(c.value,1000)} kV`))}${row(frontName(p),comp(fk,c=>`${fmt(c.value,1e-6)} µs (${signed(c.deviation_pct)}%)`))}${row('T2',comp('T2_s',c=>`${fmt(c.value,1e-6)} µs (${signed(c.deviation_pct)}%)`))}${row('Hardware / recipe',r=>r.recipe_status)}
  </tbody></table></div><div><div class="card-head tight"><h4>Stored reference waveforms</h4><div class="seg sm" role="group" aria-label="Overlay window">${['front','tail','full'].map(x=>`<button type="button" data-overlay-range="${x}" class="${x==='tail'?'active':''}">${x==='front'?'Front':x==='tail'?'Tail':'Full'}</button>`).join('')}</div></div><div id="compare-wave" class="chart">${loading()}</div><div class="legend"><span><i class="ln ref"></i>#${a.rank}</span><span><i class="ln alt"></i>#${b.rank}</span><span><i class="ln band"></i>Crest band</span></div></div></div>`;
}

/* ------------------------------------------------------------------ waveform */
export function waveformView(s){const p=s.bundle.result,r=s.row;if(!r)return resultView(s);const m=metrics(r),isLI=p.request.impulse_type==='LI',ev=p.candidates.filter(x=>x.waveform_reference);
  const markers=isLI?[['virtual_origin_s','Virtual origin O₁'],['t30_s','Rising 30%'],['t90_s','Rising 90%'],['t_peak_s','Peak'],['t50_falling_s','Falling 50%']]:[['beginning_s','Beginning'],['t30_s','Rising 30%'],['t90_s','Rising 90%'],['t_peak_s','Peak / Tp'],['t50_falling_s','Falling 50%']];
  return head('Waveform analysis',`${p.request.impulse_type} reference waveform`,`Exact stored samples for configuration #${r.rank}. Every marker and time parameter comes from the saved evaluator record.`,`<label class="inline-select">Configuration <select id="wave-candidate">${ev.map(x=>`<option value="${x.candidate_id}" ${x.candidate_id===r.candidate_id?'selected':''}>#${x.rank} · ${x.configuration.stages} st · ${x.configuration.front_per_stage_ohm}/${tailLabel(x)} Ω · ${statusText(x.assessment.compliance_status)}</option>`).join('')}</select></label>`)+
  `<section class="card chart-card"><div class="chart-tools"><div class="seg" role="group" aria-label="Time window">${['front','tail','full'].map(x=>`<button type="button" data-range="${x}" class="${s.range===x?'active':''}" aria-pressed="${s.range===x}">${x==='front'?(isLI?'Front':'Rise & peak'):x==='tail'?'Tail':'Full record'}</button>`).join('')}${typeof s.range==='object'&&s.range?'<button type="button" class="active" data-range="tail" aria-label="Reset zoom">Zoomed · reset</button>':''}</div><label class="check-row sm"><input type="checkbox" id="toggle-markers" ${s.markers!==false?'checked':''}> Markers & dimensions</label><span class="micro">Drag across the plot to zoom · double-click to reset · hover for exact samples</span></div>
  <div id="analysis-wave" class="chart">${loading()}</div><div class="legend"><span><i class="ln ref"></i>Saved RLC reference (${(r.prediction?.physics_reference?.solver?.sample_count??0).toLocaleString()} samples)</span><span><i class="ln target"></i>Mathematical nominal target</span><span><i class="ln band"></i>Allowed crest band</span><span><i class="ln mk"></i>Evaluator markers</span>${isLI?'<span><i class="ln con"></i>30–90% construction line</span>':''}</div><p class="micro">The dashed double-exponential curve is one mathematical nominal target, evaluated with the same LI/SI definitions. It is not a unique required shape or an equipment prediction. The shaded band is the allowed crest interval.</p></section>
  <div class="grid-2"><section class="card"><div class="card-head"><h3>Evaluator time markers</h3>${chip(m.waveform_status==='VALID_CLEAN_FULL_IMPULSE'?'Valid clean full impulse':(m.waveform_status??'Indeterminate').replaceAll('_',' ').toLowerCase(),m.waveform_status==='VALID_CLEAN_FULL_IMPULSE'?'info':'neutral')}</div><div class="table-wrap"><table class="data compact"><thead><tr><th>Marker</th><th class="r">Time</th><th class="r">Level</th></tr></thead><tbody>${markers.map(([k,l],i)=>`<tr><td>${l}</td><td class="r num">${fmt(m[k],1e-6,6)} µs</td><td class="r num">${['0%','30%','90%','100%','50%'][i]}</td></tr>`).join('')}</tbody></table></div><p class="micro">${isLI?'T1 = (t90 − t30) / 0.6. The virtual origin O₁ = t30 − 0.3·T1; T2 runs from O₁ to the falling 50% point.':'Competition SI convention: Tp from the beginning to the peak, T2 from the beginning to falling 50%. The LI virtual origin is not used.'}</p></section>
  <section class="card"><div class="card-head"><h3>Parameters vs. limits</h3>${chip(statusText(r.assessment.compliance_status),statusTone(r.assessment.compliance_status))}</div>${paramKeys(p).map(k=>toleranceBar(k,r.score?.components?.[k],{label:paramLong(k)})).join('')}<details class="expert"><summary>Artifact & evaluation record</summary><dl class="kvs">${kv('Curve',`<code>${esc(r.waveform_reference?.curve_id)}</code>`)}${kv('File',`<code>${esc(r.waveform_reference?.path)}</code>`)}${kv('SHA-256',`<code class="hash">${esc(r.waveform_reference?.sha256)}</code>`)}${kv('Interpolation',esc(m.interpolation))}${kv('Solver',`${esc(r.prediction?.physics_reference?.solver?.method)} · rtol ${esc(r.prediction?.physics_reference?.solver?.rtol)}`)}</dl>${json(m)}</details></section></div>`;}

/* ------------------------------------------------------------------ physics + ML */
export function evidenceView(s){return head('Hybrid prediction evidence','Physics + machine learning',`How the selected configuration (#${s.row?.rank??'—'}) was predicted and checked. The reference waveform — not the ML estimate — decides compliance.`)+`<div id="evidence-content">${loading()}</div>`;}
export function evidenceContent(e,s){
  const p=s.bundle.result,r=s.row,m=metrics(r),ml=r.prediction?.ml_prediction,b=e.baseline,card=e.model_card,fk=frontKey(p),pr=r.prediction??{},comps=r.score?.components??{};
  const ood=pr.reason_codes?.includes('OUTSIDE_TRAINING_SUPPORT'),dis=r.reason_codes.includes('ML_REFERENCE_COMPLIANCE_DISAGREEMENT');
  const params=[['crest',b?.crest_V,ml?.crest_V,m.crest_magnitude_V],[fk,b?.front_s,ml?.[fk],m[fk]],['T2_s',b?.T2_s,ml?.T2_s,m.T2_s]];
  const values=(i,missing)=>`<dl class="kvs tight">${params.map(([k,...v])=>{const [u,sc]=paramUnit(k);return kv(paramLabel(k),Number.isFinite(v[i])?`<span class="num">${fmt(v[i],sc)}</span> <small>${u}</small>`:`<span class="muted">${missing}</span>`);}).join('')}</dl>`;
  const stage=(n,title,what,body,state,cls)=>`<div class="chain-step ${cls}"><div class="chain-head"><span class="kicker">${n} · ${title}</span>${state}</div><p>${what}</p>${body}</div>`;
  return `<section class="card chain-card"><div class="card-head"><h3>Prediction chain for #${r.rank}</h3><span class="micro-inline">Left to right: fast estimate → learned correction → authoritative check</span></div><div class="chain">
  ${stage('1','Physics baseline','RC circuit formula with the loop inductance set to zero. Fast, explainable, approximate.',b?values(0,'—'):'<p class="muted small">Baseline unavailable.</p>',chip(b?'Computed':'Unavailable',b?'neutral':'caution'),'base')}
  ${stage('2','Trained ML correction',card?`${esc(card.formulation.replaceAll('_',' '))} · ${esc(card.model_family.replaceAll('_',' '))}. Learns the gap between the baseline and the full RLC simulation.`:'Learned residual predictor.',ml?values(1,'—'):`<dl class="kvs tight">${kv('T2','<span class="muted">— not used</span>')}</dl>`,ml?chip('In domain','info','dot'):chip(ood?'Outside domain · fallback':'Fallback','caution','warn'),'ml')}
  ${stage('3','Reference waveform','Full RLC simulation of this exact setting, timed by the original evaluator. Decides compliance.',values(2,'—'),chip(`Compliance: ${statusText(r.assessment.compliance_status)}`,statusTone(r.assessment.compliance_status)),'ref')}</div></section>
  ${dis?`<div class="note caution">${icon('warn',16)}<span><b>Explicit disagreement.</b> ML scalar limits: <b>${r.ml_score?.scalar_limits_pass?'pass':'fail'}</b>. Saved reference waveform: <b>${statusText(r.assessment.compliance_status).toLowerCase()}</b>. The parameter values and unchanged limits appear below. The reference decides; the ML scalar decision is retained, not hidden.</span></div>`:''}
  ${!ml?`<div class="note caution">${icon('warn',16)}<span><b>${ood?'Outside the trained model’s support.':'Learned prediction unavailable.'}</b> ${pr.status==='ABSTAIN_UNSUPPORTED_WAVEFORM'?'The waveform is unsupported; no prediction is forced.':'The documented serving policy uses the physics result. No learned estimate is shown.'} <code>${esc((pr.reason_codes??[]).join(' · '))}</code></span></div>`:''}
  <section class="card"><div class="card-head"><h3>Where each layer lands</h3><div class="legend inline"><span><i class="dot base"></i>Physics baseline</span><span><i class="dot ml"></i>Trained ML</span><span><i class="dot ref"></i>Reference (authoritative)</span><span><i class="ln band"></i>Allowed</span></div></div><div class="dot-grid">${params.map(([k,bv,mv,rv])=>`<div><h4>${paramLong(k)}</h4><p class="micro dot-sub">Target ${fmt(comps[k]?.target,paramUnit(k)[1],3)} ${paramUnit(k)[0]}${comps[k]?` · allowed ${fmt(comps[k].limits[0],paramUnit(k)[1],3)} – ${fmt(comps[k].limits[1],paramUnit(k)[1],3)}`:''}</p>${dotRows(k,{limits:comps[k]?.limits,target:comps[k]?.target??(k==='crest'?p.request.target_crest_V:null),rows:[{label:'Physics baseline',value:bv,kind:'base'},{label:'Trained ML',value:mv,kind:'ml'},{label:'Reference',value:rv,kind:'ref'}]})}</div>`).join('')}</div></section>
  <div class="grid-2"><section class="card"><div class="card-head"><h3>Exact values</h3></div><div class="table-wrap"><table class="data compact"><thead><tr><th>Parameter</th><th class="r">RC baseline · L = 0</th><th class="r">Trained ML</th><th class="r">Reference</th><th class="r">ML − reference</th></tr></thead><tbody>${[['Crest · kV',b?.crest_V,ml?.crest_V,m.crest_magnitude_V,1000],['Voltage gain',b?.gain,ml?.gain,pr.physics_reference?.voltage_gain,1],[`${frontName(p)} · µs`,b?.front_s,ml?.[fk],m[fk],1e-6],['T2 · µs',b?.T2_s,ml?.T2_s,m.T2_s,1e-6]].map(([n,x,y,z,sc])=>`<tr><td>${n}</td><td class="r num">${fmt(x,sc,6)}</td><td class="r num">${fmt(y,sc,6)}</td><td class="r num"><b>${fmt(z,sc,6)}</b></td><td class="r num">${Number.isFinite(y)&&Number.isFinite(z)?signed((y-z)/sc,6):'—'}</td></tr>`).join('')}<tr><td>Compliance decision</td><td class="r">Baseline only</td><td class="r">${r.ml_score?chip(r.ml_score.scalar_limits_pass?'Scalar pass':'Scalar fail',r.ml_score.scalar_limits_pass?'neutral':'caution'):'No ML decision'}</td><td class="r">${chip(statusText(r.assessment.compliance_status),statusTone(r.assessment.compliance_status))}</td><td></td></tr></tbody></table></div><p class="micro">ML scalars are separate estimates and are never attached to the plotted reference curve. Models are trained on versioned RLC simulations.</p></section>
  <section class="card"><div class="card-head"><h3>Model card</h3>${card?chip(card.real_data_calibrated?'Calibrated':'Simulation-trained','caution'):''}</div>${card?`<dl class="kvs">${kv('Model',`${esc(card.model_family.replaceAll('_',' '))}`)}${kv('Formulation',esc(card.formulation.replaceAll('_',' ')))}${kv('Impulse · topology',`${esc(card.mode)} · ${esc(card.topology_version)}`)}${kv('Train / validation / test rows',`<span class="num">${Object.values(card.split_counts).map(v=>v.toLocaleString()).join(' / ')}</span>`)}${kv('Domain state',ml?'Inside support':ood?'Outside support → physics fallback':'Fallback')}${kv('Model ID',`<code>${esc(card.model_id)}</code>`)}</dl><h4>Held-out ${esc(card.mode)} simulation error</h4><div class="mini-tiles">${[['Crest MAE','crest_kV','MAE','kV'],[`${frontName(p)} MAE`,'front_us','MAE','µs'],['T2 MAE','tail_us','MAE','µs'],[`${frontName(p)} P95`,'front_us','P95_absolute_error','µs'],['T2 P95','tail_us','P95_absolute_error','µs'],['Test rows','n',null,'']].map(([l,k,mm,u])=>`<div><small>${l}</small><b class="num">${fmt(mm?card.test_metrics[k]?.[mm]:card.test_metrics[k],1,4)}</b><span>${u}</span></div>`).join('')}</div><p class="micro">Grouped-setup held-out errors on simulator emulation. Not laboratory accuracy and not a confidence percentage. ${esc(card.uncertainty_status)}.</p><details class="expert"><summary>Full card & provenance</summary>${json(card)}</details>`:`<p class="muted small">No matching model card for this recorded artifact; current model evidence is not substituted.</p>`}<h4>Support policy</h4><p class="small muted">The serving layer checks trained feature ranges, nearest-neighbour distance and observed stage/resistor categories. Outside support, Physics supplies the value. Unsupported waveforms remain indeterminate.</p>${b?`<p class="micro">Baseline <code>${esc(b.version)}</code></p>`:`<p class="note">Baseline unavailable: ${esc(e.baseline_unavailable_reason??'No baseline recorded')}</p>`}</section></div>`;
}

/* ------------------------------------------------------------------ complete search */
export function searchView(s){const p=s.bundle.result,rows=p.candidates;const stages=[...new Set(rows.map(r=>r.configuration.stages))].sort((a,b)=>a-b);
  return head('Exhaustive search','Every declared configuration',`All ${rows.length} catalogue entries for ${p.request.impulse_type} · ${p.request.topology_id}, kept in the optimizer's original rank order, including failures and indeterminate results.`)+
  `<div class="grid-search"><section class="card"><div class="card-head"><h3>Search funnel</h3><span class="micro-inline">${p.search.pruned_count} pruned</span></div>${funnel(p,rows)}<dl class="kvs tight">${kv('Strategy',`<code>${esc(p.search.strategy)}</code>`)}${kv('Approved recipes',`<span class="num">${p.search.approved_recipe_count}</span>`)}${kv('Best reference J',`<span class="num">${fmt((p.best_configuration??p.closest_noncompliant)?.score?.J,1,6)}</span>`)}</dl></section>
  <section class="card"><div class="card-head"><h3>Timing tolerance window</h3><div class="legend inline"><span><i class="sw-dot pass"></i>Compliant</span><span><i class="sw-dot fail"></i>Not compliant</span><span><i class="sw-dot crest"></i>Crest outside band</span></div></div>${toleranceScatter(rows,p,s.row?.candidate_id)}<p class="micro">Each point is one evaluable configuration, plotted as ${frontName(p)} and T2 deviation from target. The dashed box is the allowed ${frontName(p)}/T2 window; filled points are numerically compliant (crest inside its band too). Points beyond the plotted range are pinned to the edge and faded.</p></section></div>
  <section class="card search-space"><div class="card-head"><h3>Search space</h3><div class="legend inline"><span><i class="sq pass"></i>Compliant</span><span><i class="sq fail"></i>Not compliant</span><span><i class="sq indet"></i>Indeterminate</span><span><i class="sq constraint"></i>Constraint not met</span></div></div><p class="card-sub">Rows are active stages; columns are grouped by front resistor, then tail resistor (Ω per stage). Each cell shows the optimizer’s original rank. Click a cell to inspect it.</p>${searchMatrix(rows,s.row?.candidate_id)}</section>
  <section class="card"><div class="card-head"><h3>Candidate table</h3><div class="filters"><select id="search-filter" aria-label="Filter by numerical status"><option value="all">All statuses</option><option value="PASS">Numerical passes</option><option value="FAIL">Numerical failures</option><option value="INDETERMINATE">Indeterminate</option></select><select id="search-stages" aria-label="Filter by active stages"><option value="all">All stages</option>${stages.map(n=>`<option value="${n}">${n} stages</option>`).join('')}</select><select id="search-sort" aria-label="Display sort"><option value="rank">Sort: original rank</option><option value="J">Sort: score J</option><option value="t2">Sort: |T2 deviation|</option><option value="energy">Sort: stored energy</option><option value="stages">Sort: stages</option></select></div></div><p class="micro" id="search-note">Showing ${rows.length} of ${rows.length}. Display sorting never changes the rank column, which is the optimizer's order.</p><div id="search-table">${candidateTable(rows,p,{expert:true,selected:s.row?.candidate_id})}</div></section>
  <details class="card fold-card"><summary><h3>Frozen ranking policy & versions</h3><small>${esc(p.ranking_policy?.version)}</small></summary><p class="small">${esc(p.ranking_policy?.primary)}</p><p class="small muted">Tie-breakers: ${esc((p.ranking_policy?.tie_breakers??[]).join(' → '))}</p>${json(p.ranking_policy)}${json(p.provenance)}</details>`;}

/* ------------------------------------------------------------------ history */
export function historyView(rows,current){return head('Saved runs','Engineering records','Every run and opened scenario is saved with its original request, versions and waveform bundle. Reopening never silently recomputes.',button(`${icon('plus',14)} New configuration`,'plan','primary'))+
  `<section class="card"><div class="card-head"><div class="seg" role="group" aria-label="Impulse filter">${[['all','All'],['LI','LI'],['SI','SI']].map(([v,l],i)=>`<button type="button" data-history-type="${v}" class="${i?'':'active'}">${l}</button>`).join('')}</div><div class="filters"><select id="history-source" aria-label="Filter by source"><option value="all">All sources</option><option value="LIVE_OPTIMIZATION">Computed locally</option><option value="SYNTHETIC_DEMO">Saved simulations</option><option value="REOPENED_EVIDENCE">Reopened evidence</option></select><input id="history-search" type="search" placeholder="Search reference or topology" aria-label="Search saved runs"></div></div><div id="history-rows">${historyRows(rows,current)}</div></section>`;}
export function historyRows(rows,current){if(!rows.length)return `<div class="empty-inline">${icon('history',28)}<h3>No matching records</h3><p class="muted">Run an optimisation or open a synthetic scenario. Each result is saved with its evidence and timestamp.</p>${button('Open scenarios','demos','primary')}</div>`;
  return `<div class="table-wrap"><table class="data history"><thead><tr><th>Saved</th><th>Test</th><th class="r">Requested crest</th><th>Outcome</th><th>Profile · versions</th><th></th></tr></thead><tbody>${rows.map(r=>{const q=r.request??{},ok=r.result_status==='NUMERICALLY_COMPLIANT_PROVISIONAL',ns=r.result_status==='NO_COMPLIANT_CONFIGURATION';return `<tr class="${r.run_id===current?'selected':''}"><td class="small"><span class="num">${date(r.created_at)}</span><span class="cid">${r.source==='SYNTHETIC_DEMO'?'Saved simulation · not timed':r.source==='REOPENED_EVIDENCE'?'Reopened evidence':`Computed locally${r.elapsed_seconds?` · ${fmt(r.elapsed_seconds,1,1)} s`:''}`}${r.run_id===current?' · open now':''}</span></td><td><span class="mode-pill">${esc(q.impulse_type)}</span> <b>${esc(q.request_id)}</b><span class="cid">DUT ${fmt(q.setup?.dut_capacitance_F,1e-12)} pF · L ${fmt(q.setup?.loop_inductance_H,1e-6)} µH · ${esc(q.topology_id)} · ${esc(q.catalog_scope)}</span></td><td class="r num">${q.polarity===-1?'−':'+'}${fmt(q.target_crest_V,1000)} kV</td><td><div class="chips">${r.status!=='COMPLETED'?chip(r.status,r.status==='FAILED'?'fail':'neutral'):ok?chip('Compliant setting','pass','check'):ns?chip('No solution','fail','cross'):chip(r.result_status??'—','neutral')}${r.status==='COMPLETED'?chip('Model prediction','neutral'):''}</div></td><td class="small wrap">${esc(q.equipment_profile_id)}<span class="cid">optimizer ${esc(r.optimizer_version??'—')} · app ${esc(r.application_version)}</span></td><td class="r nowrap"><button type="button" class="btn sm" data-open-run="${r.run_id}">Open</button>${current&&r.run_id!==current&&r.status==='COMPLETED'?` <button type="button" class="btn ghost sm" data-compare-run="${r.run_id}">Compare</button>`:''}</td></tr>`;}).join('')}</tbody></table></div>`;}

/* ------------------------------------------------------------------ measured data */
export function measuredView(s){const has=!!s.bundle?.result,r=s.row;return head('Waveform Review & Evidence','Acquired waveform analysis','Import a waveform with its actual configuration and acquisition metadata.')+
  `<p class="micro">Raw traces, acquisition metadata and diagnostic comparisons are preserved together.</p>
  <div class="attach-bar">${has?`<span>Attaching to <b>${esc(s.bundle.result.request.request_id)}</b> · saved configuration <b>#${r?.rank??'—'}</b> (${r?`${r.configuration.stages} stages, ${fmt(r.configuration.stage_charge_V,1000)} kV/stage`:'none'})</span>`:`<span>${icon('info',14)} Open or compute a run first — measurements attach to a saved result.</span>${button('Saved runs','history','sm')}`}</div>
  <div class="steps-3"><section class="card step-card"><div class="step-tag">1</div><h3>Raw waveform export</h3><p class="small muted">CSV with time and voltage columns. The original file is archived byte-for-byte; samples are not sorted, filtered or repaired.</p><label class="drop"><input id="measurement-csv" type="file" accept=".csv,text/csv" aria-label="Measured waveform CSV">${icon('down',20)}<span>Choose CSV file</span><small>Up to 10 MB</small></label></section>
  <section class="card step-card"><div class="step-tag">2</div><h3>Acquisition metadata</h3><div class="field"><label for="evidence-kind">Template evidence kind</label><select id="evidence-kind"><option value="SYNTHETIC_TEST">Synthetic test / simulator export</option><option value="BENCH_EXPERIMENT">Bench experiment</option><option value="ACTUAL_LABORATORY_EXPORT">Declared CPRI export</option></select></div><p class="small muted">Actual generator settings, setup ID, units, divider scaling and calibration references are required by the measured-data contract.</p><label class="drop"><input id="measurement-metadata" type="file" accept=".json,application/json" aria-label="Measurement metadata JSON">${icon('layers',20)}<span>Load metadata JSON</span><small>or edit below</small></label>${button(`${icon('down',14)} Download template`,'measurement-template','ghost sm')}</section>
  <section class="card step-card wide"><div class="step-tag">3</div><h3>Review & archive</h3><textarea id="measurement-json" aria-label="Measurement metadata editor" placeholder="Load your metadata JSON, or download the template and fill in the actual acquisition details."></textarea><div id="measurement-error" role="alert"></div><button type="button" class="btn primary" id="import-measurement" ${has?'':'disabled aria-disabled="true" title="Open or compute a run first"'}>Archive & compare ${icon('arrow',14)}</button><p class="micro">${has?'Declared actual settings drive the comparison; the saved selection is only context.':'Disabled: no saved run is open.'}</p></section></div>
  <div id="saved-measurements"></div><div id="measurement-result"></div>`;}

/* ------------------------------------------------------------------ misc states */
export function empty(meta){return `<div class="empty"><div class="empty-ic">${icon('wave',30)}</div><h1>No test open yet</h1><p>Plan an impulse test, or open a synthetic scenario to see a recommendation, its waveform and the full evidence trail.</p><div class="actions center">${button(`${icon('plus',14)} Plan a test`,'plan','primary')}${button('Open scenarios','demos','ghost')}</div></div>`;}
export function loading(){return '<div class="loading"><span class="spinner"></span>Loading verified local artifacts…</div>';}
export function progressView(bundle){const r=bundle.run,text=r.progress??'',match=text.match(/Evaluated (\d+)\s*\/\s*(\d+)/),ended=/END/.test(text),started=/START/.test(text)||!!match;
  const stage=ended?2:started?1:0,percent=ended?100:match?Number(match[1])/Number(match[2])*100:started?2:0,message=text.replace(/^\[[^\]]*\]\s*/,'');
  return `<section class="progress"><div class="eyebrow">Optimisation running · local process</div><h1>Evaluating the declared catalogue</h1><p class="muted">The setup is fixed. Every configuration is predicted (Physics + ML), simulated as a reference waveform and timed by the evaluator. Actual progress from the optimiser log — no estimated percentages.</p><ol class="pipeline three">${['Start the versioned Physics + ML stack','Predict, simulate & evaluate every configuration','Rank and save result + waveforms'].map((t,i)=>`<li class="${i<stage?'done':i===stage?'now':''}">${t}</li>`).join('')}</ol><div class="bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(percent)}"><span style="width:${percent}%"></span></div><div class="progress-meta"><span>${esc(message||'Queued')}</span><span class="num">${r.elapsed_seconds?`${fmt(r.elapsed_seconds,1,1)} s`:'starting…'}</span></div><p class="micro">Closing this view does not cancel the search. It remains available from Saved runs. Results are shown only after the complete result and every waveform are saved.</p></section>`;}
export const demoTone=t=>t==='NO SOLUTION'?'fail':t==='START HERE'?'pass':t==='EVIDENCE'||t==='FALLBACK'?'ml':t==='HARDWARE'||t==='BOUNDARY'?'caution':'info';
export function demoLibrary(demos){const groups=[['Core decision',['si','li','crest','load']],['Honest failure',['li_single','infeasible','approved']],['Evidence & domain',['li_disagreement','ood']],['Boundaries & topology',['band','low','output_shunt']]];
  return `<div class="demo-groups">${groups.map(([g,ids])=>`<div><h4>${g}</h4><div class="demo-grid">${ids.map(id=>demos.find(d=>d.id===id)).filter(Boolean).map(d=>`<button type="button" class="demo-card" data-demo="${d.id}"><span class="sc-tag ${demoTone(d.tag)}">${esc(d.tag)}</span><b>${esc(d.title)}</b><span>${esc(d.story)}</span><small class="num">${esc(d.label)}</small></button>`).join('')}</div></div>`).join('')}</div><p class="micro">Each scenario opens the exact synthetic optimizer bytes and waveforms. Nothing is recalculated or retimed.</p>`;}

export function recipeControls(q,p){const active=q.recipe_ids??['DEV_UNIFORM_SINGLE_v2'];return `<div id="recipe-controls"><div class="sub-head"><h3>Circuit arrangements</h3><span class="micro-inline">Select at least one</span></div><div class="option-list">${p.topology.development_recipes.filter(r=>['DEV_UNIFORM_SINGLE_v2','HYP_LI_TAIL_180_PAR_520_v1'].includes(r.id)).map(r=>{const allowed=r.allowed_impulse_types.includes(q.impulse_type)&&r.allowed_topologies.includes(q.topology_id);return `<label class="option ${allowed?'':'unavailable'}"><input type="checkbox" data-recipe value="${esc(r.id)}" ${allowed&&active.includes(r.id)?'checked':''} ${allowed?'':'disabled'}><span><b>${r.id==='DEV_UNIFORM_SINGLE_v2'?'One front and one tail component per active stage':'Parallel LI tail: 180 || 520 Ω per stage'}</b><small><code>${esc(r.id)}</code>${allowed?'':` · ${r.id==='HYP_LI_TAIL_180_PAR_520_v1'?'LI with GSHUNT only':'not available for this impulse/topology'}`}</small></span></label>`;}).join('')}</div><p class="micro">The parallel tail needs both components at every active stage.</p></div>`;}
export function componentBill(row){return `<div class="note"><div><b>Configuration component list</b><p>${(row.component_bill_of_materials??[]).map(x=>`${fmt(x.required_count)} × ${fmt(x.component_ohm)} Ω`).join(' · ')||'Not recorded'}</p><p>Tail equivalent: ${fmt(row.tail_recipe?.equivalent_per_stage_ohm??row.tail_recipe?.per_stage_ohm)} Ω/stage.</p></div></div>`;}
