"""Immutable-data training, validation-only selection, and v3 CLI."""
from __future__ import annotations

import argparse
import hashlib
import inspect
import json
import math
import pickle
import time
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Sequence

import numpy as np

from .features import TARGET_COLUMNS
from .models import FAMILIES, FORMULATIONS, NetworkModel, make_candidates
from .registry import file_hash, register_model, runtime_versions, source_fingerprint


ROUTES = tuple((domain, mode, topology) for domain in ("cpri_0p5uf", "research_3uf") for mode in ("LI", "SI") for topology in ("GSHUNT_v0", "OSHUNT_v0"))
SPLITS = ("train", "validation", "test")
_COMPLETED_DATASET_STATUSES = frozenset({"COMPLETE", "STAGE_COMPLETE", "FULL_DESIGN_COMPLETE"})
_DATASET_SOURCE_KEYS = (
    "powernext_v3/dataset.py",
    "powernext_v3/features.py",
    "powernext_v3/networks.py",
    "powernext_v3/physics.py",
    "powernext_v3/profiles.py",
)
_DEDUP_LABEL_RTOL = 1.0e-8
_DEDUP_LABEL_ATOL = {"gain": 1.0e-10, "front_us": 1.0e-7, "tail_us": 1.0e-5}
_MODE_BOUNDS = {
    "LI": {"front_us": (0.84, 1.56), "tail_us": (40.0, 60.0)},
    "SI": {"front_us": (200.0, 300.0), "tail_us": (1000.0, 4000.0)},
}


def _progress(message: str) -> None:
    """Emit a machine-readable-friendly human heartbeat for long runs."""

    print(f"[{datetime.now(timezone.utc).isoformat(timespec='seconds')}] v3-ml {message}", flush=True)


def _json_write(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True, allow_nan=False), encoding="utf-8")


def _digest(value: Any) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()).hexdigest()


def _route(row: Mapping[str, Any]) -> tuple[str | None, str | None, str | None]:
    return row.get("domain_id"), row.get("mode", row.get("impulse_type")), row.get("topology", row.get("topology_id"))


def _eligible(row: Mapping[str, Any]) -> bool:
    value = row.get("eligible", row.get("regression_eligible", True))
    if value is False:
        return False
    if row.get("status") is not None and str(row["status"]).upper() in {
        "INVALID",
        "INVALID_OR_UNSUPPORTED",
        "FAILED",
        "INELIGIBLE",
        "TRUNCATED",
    }:
        return False
    return isinstance(row.get("features"), Mapping) and all(row.get(name) is not None for name in TARGET_COLUMNS)


def _validate_dataset_source_contract(manifest: Mapping[str, Any]) -> None:
    """Require that production rows were generated by the current v3 contract.

    Dataset generation is deliberately immutable.  A completed manifest from a
    previous numerical contract must not be accepted merely because its JSONL
    hash is intact: the labels could have been produced by different feature,
    network, profile, or simulator code.  The explicit fixture writer marks
    test-only data and is the sole exception to this source check.
    """

    source_hashes = manifest.get("source_hashes")
    if not isinstance(source_hashes, Mapping):
        raise ValueError("Production dataset manifest is missing source_hashes")
    package_root = Path(__file__).resolve().parents[1]
    missing: list[str] = []
    mismatched: list[str] = []
    for relative in _DATASET_SOURCE_KEYS:
        expected = source_hashes.get(relative)
        path = package_root / Path(relative)
        if not expected or not path.is_file():
            missing.append(relative)
            continue
        actual = file_hash(path)
        if actual != expected:
            mismatched.append(relative)
    if missing:
        raise ValueError("Production dataset manifest is missing source hashes: " + ", ".join(missing))
    if mismatched:
        raise ValueError("Dataset source contract differs from current v3 code: " + ", ".join(mismatched))

    recorded_physics = manifest.get("physics_source_fingerprint")
    provenance = manifest.get("provenance")
    if recorded_physics is None and isinstance(provenance, Mapping):
        recorded_physics = provenance.get("physics_source_fingerprint")
    if not isinstance(recorded_physics, Mapping):
        raise ValueError("Production dataset manifest is missing physics_source_fingerprint")
    from .physics import source_fingerprint as current_physics_fingerprint

    current_physics = current_physics_fingerprint()
    if dict(recorded_physics) != dict(current_physics):
        raise ValueError("Dataset Physics source fingerprint differs from current v3 Physics")


def load_rows(data_dir: str | Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Read a completed immutable JSONL dataset and verify its contract.

    ``STAGE_COMPLETE`` and ``FULL_DESIGN_COMPLETE`` are valid data-worker
    completion states.  ``IN_PROGRESS``, ``FAILED``, a missing manifest, a
    missing row hash, or a stale source contract fail closed.  The only
    source-contract exception is a manifest explicitly emitted by
    ``write_rows_jsonl(..., fixture=True)`` for the tiny API tests.
    """

    source = Path(data_dir)
    rows_path = source if source.is_file() else source / "rows.jsonl"
    if not rows_path.is_file():
        raise FileNotFoundError(f"Missing dataset rows.jsonl: {rows_path}")
    manifest_path = rows_path.parent / "manifest.json"
    if not manifest_path.is_file():
        raise ValueError(f"Dataset manifest.json is required: {manifest_path}")
    try:
        manifest: dict[str, Any] = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid dataset manifest: {manifest_path}") from exc
    status = manifest.get("status")
    if status not in _COMPLETED_DATASET_STATUSES:
        raise ValueError(f"Dataset manifest status is not complete: {status!r}")
    expected = manifest.get("rows_sha256")
    if not isinstance(expected, str) or not expected:
        raise ValueError("Dataset manifest is missing rows_sha256")
    actual_rows_hash = file_hash(rows_path)
    if actual_rows_hash != expected:
        raise ValueError("Dataset rows hash does not match its manifest")
    fixture = manifest.get("fixture_only") is True and manifest.get("dataset_kind") == "EXPLICIT_TEST_FIXTURE"
    if not fixture:
        _validate_dataset_source_contract(manifest)
    manifest_file_hash = file_hash(manifest_path)
    rows: list[dict[str, Any]] = []
    with rows_path.open("r", encoding="utf-8") as stream:
        for line_no, line in enumerate(stream, 1):
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSONL at line {line_no}") from exc
            if not isinstance(row, dict):
                raise ValueError(f"JSONL row {line_no} is not an object")
            rows.append(row)
    declared_count = manifest.get("row_count")
    if declared_count is not None and int(declared_count) != len(rows):
        raise ValueError("Dataset row_count does not match rows.jsonl")
    manifest = dict(manifest, rows_sha256=actual_rows_hash, row_count=len(rows), data_path=str(rows_path.resolve()), manifest_sha256=manifest_file_hash)
    return rows, manifest


def write_rows_jsonl(rows: Iterable[Mapping[str, Any]], output_dir: str | Path, *, manifest: Mapping[str, Any] | None = None, fixture: bool = False) -> dict[str, Any]:
    """Write immutable rows, optionally marking a tiny explicit test fixture.

    Production data should be written by ``powernext_v3.dataset`` so its
    source contract and completion metadata are present.  ``fixture=True`` is
    intentionally explicit and exists only for API tests.
    """

    out = Path(output_dir)
    if out.exists():
        raise FileExistsError(f"Immutable dataset destination exists: {out}")
    out.mkdir(parents=True)
    rows_list = [dict(row) for row in rows]
    row_path = out / "rows.jsonl"
    with row_path.open("w", encoding="utf-8", newline="\n") as stream:
        for row in rows_list:
            stream.write(json.dumps(row, sort_keys=True, allow_nan=False) + "\n")
    result = dict(manifest or {}, schema_version="ml_dataset_v3", status="COMPLETE", row_count=len(rows_list), rows_sha256=file_hash(row_path))
    if fixture:
        result.update(dataset_kind="EXPLICIT_TEST_FIXTURE", fixture_only=True)
    _json_write(out / "manifest.json", result)
    return result


def _row_key(row: Mapping[str, Any], index: int) -> str:
    return str(row.get("row_id", row.get("id", f"row_{index:09d}")))


def _group_key(row: Mapping[str, Any], index: int) -> str:
    for key in ("group_id", "request_group_id", "setup_family_id", "physical_shape_id"):
        value = row.get(key)
        if value not in (None, ""):
            return str(value)
    return _row_key(row, index)


def _identity_tokens(row: Mapping[str, Any]) -> list[tuple[str, str]]:
    """Return split-integrity identities carried by a dataset row.

    The data worker freezes a union of response shape and setup-family
    identities into ``group_id``.  The source identities are retained as
    separate fields for auditability, so both the union id and each source
    identity must remain in one partition.  A few explicit aliases are
    accepted for older immutable row snapshots.
    """

    tokens: list[tuple[str, str]] = []

    def add(kind: str, value: Any) -> None:
        if value is None or (isinstance(value, str) and value == ""):
            return
        if isinstance(value, (Mapping, list, tuple)):
            value = json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False)
        tokens.append((kind, str(value)))

    for key in (
        "group_id",
        "response_group_id",
        "response_group_key",
        "response_identity",
        "response_shape_id",
        "physical_shape_id",
        "shape_id",
        "input_shape_id",
    ):
        add(key, row.get(key))
    for key in ("setup_family_id", "setup_family_key", "setup_family", "setup_id"):
        add(key, row.get(key))
    setup = row.get("setup")
    if isinstance(setup, Mapping):
        add("setup_family_id", setup.get("setup_family_id"))
        add("setup_id", setup.get("setup_id"))
    split_audit = row.get("split_audit")
    if isinstance(split_audit, Mapping):
        add("response_group_key", split_audit.get("response_group_key"))
        add("setup_family_key", split_audit.get("setup_family_key"))
    return tokens


def _validate_explicit_split_integrity(rows: Sequence[Mapping[str, Any]], assignments: Sequence[str]) -> None:
    """Reject any explicit partition that separates one physical identity."""

    seen: dict[tuple[str, str], tuple[str, int]] = {}
    for index, (row, assignment) in enumerate(zip(rows, assignments)):
        for identity in _identity_tokens(row):
            previous = seen.get(identity)
            if previous is not None and previous[0] != assignment:
                kind, value = identity
                raise ValueError(
                    f"Explicit split crosses {kind}={value!r}: "
                    f"row {previous[1]} is {previous[0]}, row {index} is {assignment}"
                )
            seen.setdefault(identity, (assignment, index))


def _frozen_group_values(rows: Sequence[Mapping[str, Any]]) -> list[str]:
    """Build deterministic connected components from all split identities."""

    parent = list(range(len(rows)))

    def find(index: int) -> int:
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    def union(left: int, right: int) -> None:
        left_root, right_root = find(left), find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    first_seen: dict[tuple[str, str], int] = {}
    for index, row in enumerate(rows):
        for identity in _identity_tokens(row):
            previous = first_seen.get(identity)
            if previous is None:
                first_seen[identity] = index
            else:
                union(index, previous)
    members: dict[int, list[str]] = defaultdict(list)
    for index, row in enumerate(rows):
        members[find(index)].append(_row_key(row, index))
    component_ids = {
        root: hashlib.sha256(json.dumps(sorted(member_ids), separators=(",", ":")).encode()).hexdigest()
        for root, member_ids in members.items()
    }
    return [component_ids[find(index)] for index in range(len(rows))]


def _stable_fraction(value: str, seed: int) -> float:
    digest = hashlib.sha256(f"{seed}:{value}".encode()).hexdigest()
    return int(digest[:16], 16) / float(16**16)


def _response_shape_key(row: Mapping[str, Any], index: int) -> str | None:
    """Return the worker's normalized response identity, if present.

    ``group_id`` is intentionally excluded: it may identify one request row
    even when several rows share the same response graph.  The response key
    is the identity that remains invariant across charge and polarity variants.
    """

    for key in ("response_group_key", "response_group_id", "response_identity", "response_shape_id", "physical_shape_id"):
        value = row.get(key)
        if value is not None and not (isinstance(value, str) and value == ""):
            return str(value)
    split_audit = row.get("split_audit")
    if isinstance(split_audit, Mapping):
        value = split_audit.get("response_group_key")
        if value is not None and not (isinstance(value, str) and value == ""):
            return str(value)
    return None


def _deduplicate_training_rows(
    rows: Sequence[Mapping[str, Any]], assignments: Sequence[str]
) -> tuple[list[dict[str, Any]], list[str], dict[str, Any], dict[int, dict[str, Any]]]:
    """Collapse repeated response shapes while retaining an audit trail.

    The canonical row is the lexicographically smallest ``row_id`` within a
    route/response-key group.  Labels from every eligible duplicate must agree
    within the fixed numerical tolerances; otherwise training stops rather
    than averaging incompatible physics outcomes.  Rows without a normalized
    response key remain distinct.
    """

    groups: dict[tuple[tuple[str | None, str | None, str | None], str], list[int]] = defaultdict(list)
    unkeyed: list[int] = []
    for index, row in enumerate(rows):
        response_key = _response_shape_key(row, index)
        route = _route(row)
        if response_key is None:
            unkeyed.append(index)
        else:
            groups[(route, response_key)].append(index)

    canonical_indices: set[int] = set(unkeyed)
    audit: dict[int, dict[str, Any]] = {}
    duplicate_group_count = 0
    duplicates_removed = 0
    duplicates_by_route: dict[str, int] = defaultdict(int)
    duplicate_groups_by_route: dict[str, int] = defaultdict(int)
    for (route, response_key), indices in groups.items():
        ordered = sorted(indices, key=lambda i: (_row_key(rows[i], i), i))
        canonical = ordered[0]
        canonical_indices.add(canonical)
        duplicate_group_count += int(len(ordered) > 1)
        duplicates_removed += max(0, len(ordered) - 1)
        route_id = ":".join(str(value) for value in route)
        if len(ordered) > 1:
            duplicate_groups_by_route[route_id] += 1
            duplicates_by_route[route_id] += len(ordered) - 1
        for target in TARGET_COLUMNS:
            reference = float(rows[canonical][target])
            tolerance = _DEDUP_LABEL_ATOL[target]
            for index in ordered[1:]:
                value = float(rows[index][target])
                if not np.isclose(value, reference, rtol=_DEDUP_LABEL_RTOL, atol=tolerance, equal_nan=False):
                    raise ValueError(
                        "Inconsistent duplicate labels for "
                        f"route={route_id}, response_group_key={response_key!r}, target={target}: "
                        f"canonical row {_row_key(rows[canonical], canonical)}={reference!r}, "
                        f"row {_row_key(rows[index], index)}={value!r}"
                    )
        assignments_in_group = {assignments[index] for index in ordered}
        if len(assignments_in_group) != 1:
            raise ValueError(
                f"Duplicate response group crosses explicit splits: route={route_id}, response_group_key={response_key!r}, splits={sorted(assignments_in_group)}"
            )
        for index in ordered:
            audit[index] = {
                "canonical_row_id": _row_key(rows[canonical], canonical),
                "response_group_key": response_key,
                "deduplicated": index != canonical,
            }

    for index in unkeyed:
        audit[index] = {
            "canonical_row_id": _row_key(rows[index], index),
            "response_group_key": None,
            "deduplicated": False,
        }
    canonical_order = sorted(canonical_indices)
    canonical_rows = [dict(rows[index]) for index in canonical_order]
    canonical_assignments = [assignments[index] for index in canonical_order]
    report = {
        "input_eligible_rows": len(rows),
        "canonical_rows": len(canonical_rows),
        "duplicates_removed": duplicates_removed,
        "duplicate_group_count": duplicate_group_count,
        "unkeyed_rows_retained": len(unkeyed),
        "label_tolerance": {"rtol": _DEDUP_LABEL_RTOL, "atol": dict(_DEDUP_LABEL_ATOL)},
        "canonical_policy": "lexicographically_smallest_row_id_per_route_response_group_key",
        "duplicates_removed_by_route": dict(sorted(duplicates_by_route.items())),
        "duplicate_groups_by_route": dict(sorted(duplicate_groups_by_route.items())),
    }
    return canonical_rows, canonical_assignments, report, audit


def _validate_training_scope(
    grouped: Mapping[tuple[str, str, str], Sequence[Mapping[str, Any]]],
    *,
    fixture: bool,
) -> dict[str, Any]:
    """Validate route/partition coverage before any estimator is fitted."""

    actual_routes = set(grouped)
    expected_routes = set(ROUTES)
    counts = {
        ":".join(route): {
            split: sum(1 for row in rows if row.get("split") == split)
            for split in SPLITS
        }
        for route, rows in sorted(grouped.items())
    }
    scope = {
        "kind": "EXPLICIT_TEST_FIXTURE" if fixture else "PRODUCTION_8_ROUTE",
        "fixture": fixture,
        "expected_route_count": 1 if fixture else len(ROUTES),
        "actual_route_count": len(actual_routes),
        "routes": [":".join(route) for route in sorted(actual_routes)],
        "partition_counts": counts,
    }
    if fixture:
        return scope
    missing = sorted(expected_routes - actual_routes)
    extra = sorted(actual_routes - expected_routes)
    incomplete = {
        ":".join(route): counts.get(":".join(route), {split: 0 for split in SPLITS})
        for route in sorted(expected_routes & actual_routes)
        if any(counts.get(":".join(route), {}).get(split, 0) <= 0 for split in SPLITS)
    }
    if missing or extra or incomplete:
        details = {
            "missing_routes": [":".join(route) for route in missing],
            "unexpected_routes": [":".join(route) for route in extra],
            "incomplete_routes": incomplete,
        }
        raise ValueError(
            "Production v3 training requires exactly eight routes with non-empty train/validation/test partitions: "
            + json.dumps(details, sort_keys=True)
        )
    return scope


def assign_splits(rows: Sequence[Mapping[str, Any]], seed: int = 20261010) -> list[str]:
    """Use a checked explicit split or make deterministic identity groups.

    An explicit split is trusted only after every retained group, response
    identity, and setup-family identity is proven to stay in one partition.
    Partial or invalid labels fail closed instead of silently recomputing a
    split that could hide leakage in an immutable dataset.
    """

    explicit: list[str | None] = []
    for row in rows:
        raw = row.get("split")
        if raw is None or str(raw).strip() == "":
            explicit.append(None)
            continue
        value = str(raw).strip().lower()
        value = {"val": "validation", "valid": "validation", "development": "train"}.get(value, value)
        explicit.append(value)
    present = [value for value in explicit if value is not None]
    if present:
        if len(present) != len(explicit):
            raise ValueError("Split labels must be present for every row or absent for every row")
        invalid = sorted({value for value in present if value not in SPLITS})
        if invalid:
            raise ValueError(f"Unknown explicit split labels: {invalid}")
        assignments = [str(value) for value in explicit]
        _validate_explicit_split_integrity(rows, assignments)
        return assignments
    group_values = _frozen_group_values(rows)
    assignments = []
    for group in group_values:
        z = _stable_fraction(group, seed)
        assignments.append("train" if z < 0.70 else ("validation" if z < 0.85 else "test"))
    # Tiny explicit-free fixtures still need all three gates.  Keep group
    # integrity, then move whole groups only when a split is empty.
    groups = defaultdict(list)
    for i, group in enumerate(group_values):
        groups[group].append(i)
    for needed in SPLITS:
        if needed not in assignments:
            source = next((s for s in SPLITS if s != needed and s in assignments), None)
            if source is None:
                continue
            candidate_group = next((g for g, indices in groups.items() if assignments[indices[0]] == source), None)
            if candidate_group is not None:
                for index in groups[candidate_group]:
                    assignments[index] = needed
    return assignments


def _records_for_split(rows: Sequence[Mapping[str, Any]], split: str) -> list[dict[str, Any]]:
    return [dict(row) for row, assignment in zip(rows, split_assignments(rows)) if assignment == split]


def split_assignments(rows: Sequence[Mapping[str, Any]], seed: int = 20261010) -> list[str]:
    """Alias kept separate so callers can inspect the exact split contract."""

    return assign_splits(rows, seed=seed)


def _labels(rows: Sequence[Mapping[str, Any]]) -> np.ndarray:
    return np.asarray([[float(row[name]) for name in TARGET_COLUMNS] for row in rows], dtype=float)


def _tolerances(rows: Sequence[Mapping[str, Any]], mode: str) -> np.ndarray:
    gains = np.maximum(_labels(rows)[:, 0], 1e-12)
    front_half = (_MODE_BOUNDS[mode]["front_us"][1] - _MODE_BOUNDS[mode]["front_us"][0]) / 2.0
    tail_half = (_MODE_BOUNDS[mode]["tail_us"][1] - _MODE_BOUNDS[mode]["tail_us"][0]) / 2.0
    return np.column_stack((0.03 * gains, np.full(len(rows), front_half), np.full(len(rows), tail_half)))


def _configuration(row: Mapping[str, Any]) -> Mapping[str, Any]:
    config = row.get("configuration", {})
    return config if isinstance(config, Mapping) else vars(config)


def _crest_values(rows: Sequence[Mapping[str, Any]], gain: np.ndarray) -> tuple[np.ndarray, np.ndarray] | None:
    target_values = []
    input_values = []
    for row, g in zip(rows, gain):
        config = _configuration(row)
        charge = config.get("stage_charge_V", row.get("stage_charge_V"))
        stages = config.get("stages", row.get("stages"))
        target = row.get("target_crest_V", row.get("target_V"))
        if charge is None or stages is None or target is None:
            return None
        target_values.append(float(target))
        input_values.append(float(abs(float(charge) * float(stages))))
    return np.asarray(input_values) * gain, np.asarray(target_values)


def boundary_metrics(rows: Sequence[Mapping[str, Any]], truth: np.ndarray, pred: np.ndarray, mode: str) -> dict[str, Any]:
    bounds = _MODE_BOUNDS[mode]
    front_lo, front_hi = bounds["front_us"]
    tail_lo, tail_hi = bounds["tail_us"]
    front_error = np.maximum(np.maximum(front_lo - pred[:, 1], pred[:, 1] - front_hi), 0.0)
    tail_error = np.maximum(np.maximum(tail_lo - pred[:, 2], pred[:, 2] - tail_hi), 0.0)
    truth_shape = (truth[:, 1] >= front_lo) & (truth[:, 1] <= front_hi) & (truth[:, 2] >= tail_lo) & (truth[:, 2] <= tail_hi)
    pred_shape = (pred[:, 1] >= front_lo) & (pred[:, 1] <= front_hi) & (pred[:, 2] >= tail_lo) & (pred[:, 2] <= tail_hi)
    out: dict[str, Any] = {
        "front_outside_rate": float(np.mean(front_error > 0)) if len(pred) else None,
        "tail_outside_rate": float(np.mean(tail_error > 0)) if len(pred) else None,
        "front_boundary_error_max_us": float(np.max(front_error)) if len(pred) else None,
        "tail_boundary_error_max_us": float(np.max(tail_error)) if len(pred) else None,
        "front_tolerance_normalized_boundary_error_max": float(np.max(front_error / ((front_hi - front_lo) / 2.0))) if len(pred) else None,
        "tail_tolerance_normalized_boundary_error_max": float(np.max(tail_error / ((tail_hi - tail_lo) / 2.0))) if len(pred) else None,
        "front_tolerance_normalized_boundary_error_P95": float(np.quantile(front_error / ((front_hi - front_lo) / 2.0), 0.95)) if len(pred) else None,
        "tail_tolerance_normalized_boundary_error_P95": float(np.quantile(tail_error / ((tail_hi - tail_lo) / 2.0), 0.95)) if len(pred) else None,
        "shape_false_accept": int(np.sum(~truth_shape & pred_shape)),
        "shape_false_reject": int(np.sum(truth_shape & ~pred_shape)),
        "shape_truth_pass": int(np.sum(truth_shape)),
        "shape_predicted_pass": int(np.sum(pred_shape)),
    }
    crest = _crest_values(rows, truth[:, 0])
    crest_pred = _crest_values(rows, pred[:, 0])
    if crest is not None and crest_pred is not None:
        true_crest, targets = crest
        predicted_crest, _ = crest_pred
        true_pass = (true_crest >= 0.97 * targets) & (true_crest <= 1.03 * targets)
        pred_pass = (predicted_crest >= 0.97 * targets) & (predicted_crest <= 1.03 * targets)
        out.update(
            crest_boundary_error_max_V=float(np.max(np.maximum(np.maximum(0.97 * targets - predicted_crest, predicted_crest - 1.03 * targets), 0.0))),
            crest_false_accept=int(np.sum(~true_pass & pred_pass)),
            crest_false_reject=int(np.sum(true_pass & ~pred_pass)),
        )
    else:
        out["crest_boundary_status"] = "UNAVAILABLE_WITH_ROW_SCHEMA"
    out["shape_mismatch_rate"] = float(np.mean(truth_shape != pred_shape)) if len(pred) else None
    return out


def metric_report(rows: Sequence[Mapping[str, Any]], truth: np.ndarray, pred: np.ndarray, mode: str, *, model_ood: np.ndarray | None = None) -> dict[str, Any]:
    """Compute decision metrics used for candidate selection and review."""

    truth = np.asarray(truth, dtype=float)
    pred = np.asarray(pred, dtype=float)
    if truth.shape != pred.shape or truth.ndim != 2 or truth.shape[1] != 3 or not np.isfinite(pred).all():
        raise ValueError("Invalid truth/prediction arrays")
    absolute = np.abs(truth - pred)
    tolerance = _tolerances(rows, mode)
    normalized = absolute / tolerance
    names = list(TARGET_COLUMNS)
    result: dict[str, Any] = {
        name: {
            "MAE": float(np.mean(absolute[:, i])),
            "RMSE": float(np.sqrt(np.mean(absolute[:, i] ** 2))),
            "P95_absolute_error": float(np.quantile(absolute[:, i], 0.95)),
            "max_absolute_error": float(np.max(absolute[:, i])),
            "tolerance_normalized_MAE": float(np.mean(normalized[:, i])),
            "tolerance_normalized_P95": float(np.quantile(normalized[:, i], 0.95)),
        }
        for i, name in enumerate(names)
    }
    result["n"] = len(rows)
    result["selection_score"] = float(np.mean(normalized)) if len(rows) else float("inf")
    result["boundary_errors"] = boundary_metrics(rows, truth, pred, mode)
    result["ood_count"] = int(np.sum(model_ood)) if model_ood is not None else None
    return result


def _request_group(row: Mapping[str, Any], index: int) -> str:
    for key in ("request_group_id", "request_id", "group_id", "setup_family_id"):
        if row.get(key) not in (None, ""):
            return str(row[key])
    return _row_key(row, index)


def _pairwise_rank_accuracy(rows: Sequence[Mapping[str, Any]], truth: np.ndarray, pred: np.ndarray) -> dict[str, Any]:
    """Compute secondary gain-order concordance in O(n log n) per group.

    A Fenwick tree counts strict inversions after sorting by true gain.  Pairs
    tied in either true or predicted gain are excluded exactly as in the old
    definition.  This metric is diagnostic only and never enters the primary
    candidate selection key.
    """

    def order_counts(true_values: np.ndarray, predicted_values: np.ndarray) -> tuple[int, int]:
        if len(true_values) < 2:
            return 0, 0
        truth_order = np.argsort(true_values, kind="mergesort")
        ordered_truth = true_values[truth_order]
        ordered_pred = predicted_values[truth_order]
        unique_pred, pred_ranks = np.unique(ordered_pred, return_inverse=True)
        fenwick = np.zeros(len(unique_pred) + 1, dtype=np.int64)

        def prefix(index: int) -> int:
            total = 0
            index += 1
            while index > 0:
                total += int(fenwick[index])
                index -= index & -index
            return total

        def add(index: int) -> None:
            index += 1
            while index < len(fenwick):
                fenwick[index] += 1
                index += index & -index

        discordant = 0
        comparable = 0
        previous_count = 0
        start = 0
        while start < len(ordered_truth):
            end = start + 1
            while end < len(ordered_truth) and ordered_truth[end] == ordered_truth[start]:
                end += 1
            current_ranks = pred_ranks[start:end]
            cross_pairs = previous_count * len(current_ranks)
            equal_pred = sum(prefix(int(rank)) - prefix(int(rank) - 1) for rank in current_ranks)
            greater_pred = sum(previous_count - prefix(int(rank)) for rank in current_ranks)
            comparable += cross_pairs - equal_pred
            discordant += greater_pred
            for rank in current_ranks:
                add(int(rank))
            previous_count += len(current_ranks)
            start = end
        return int(comparable), int(discordant)

    groups: dict[str, list[int]] = defaultdict(list)
    for i, row in enumerate(rows):
        groups[_request_group(row, i)].append(i)
    concordant = pairs = 0
    for indices in groups.values():
        if len(indices) < 2:
            continue
        group_pairs, group_discordant = order_counts(truth[np.asarray(indices), 0], pred[np.asarray(indices), 0])
        pairs += group_pairs
        concordant += group_pairs - group_discordant
    if pairs == 0:
        return {"status": "UNAVAILABLE_NO_COMPARABLE_REQUEST_PAIRS", "pair_count": 0, "retention": None, "scope": "within_request_group", "algorithm": "fenwick_exact_non_tied_pairs"}
    return {"status": "SECONDARY_GAIN_ORDER_PROXY", "pair_count": pairs, "retention": float(concordant / pairs), "scope": "within_request_group", "algorithm": "fenwick_exact_non_tied_pairs"}


_SELECTION_TARGET_V = 1_000_000.0
_MIN_GROUP_COVERAGE = 5
_SELECTION_SENTINEL = 1.0e9


def _charge_cap_for_row(row: Mapping[str, Any]) -> tuple[float, int] | None:
    """Return the profile charge cap and stage count for one input row."""

    config = _configuration(row)
    try:
        stages = int(config.get("stages", row.get("stages")))
        if stages <= 0 or float(config.get("stages", row.get("stages"))) != stages:
            return None
        from .profiles import get_profile

        profile = get_profile(str(row.get("domain_id", "cpri_0p5uf")))
        cap = min(
            float(profile.stage_charge_max_V),
            float(profile.summed_charge_max_V) / stages,
            math.sqrt(2.0 * float(profile.stage_energy_max_J) / float(profile.stage_capacitance_F)),
            math.sqrt(2.0 * float(profile.total_energy_max_J) / (stages * float(profile.stage_capacitance_F))),
        )
    except (AttributeError, KeyError, TypeError, ValueError, ZeroDivisionError):
        return None
    if not math.isfinite(cap) or cap <= 0:
        return None
    return cap, stages


def _fixed_target_score(gain: float, front_us: float, tail_us: float, charge_cap_V: float, stages: int, mode: str, target_V: float) -> dict[str, Any]:
    """Score one waveform at the explicit held-out target and profile cap.

    The formula is the same normalized ``J``/scalar pass policy used by the
    optimizer's legacy assessment.  Gain determines the charge required to
    reach the target; when that charge exceeds the profile cap, the crest at
    the cap is scored and the candidate cannot pass the crest limit.
    """

    try:
        gain = float(gain)
        front_us = float(front_us)
        tail_us = float(tail_us)
        charge_cap_V = float(charge_cap_V)
        target_V = float(target_V)
    except (TypeError, ValueError):
        return {"valid": False, "J": _SELECTION_SENTINEL, "pass": False}
    if not all(math.isfinite(value) and value > 0 for value in (gain, front_us, tail_us, charge_cap_V, target_V)):
        return {"valid": False, "J": _SELECTION_SENTINEL, "pass": False}
    if mode not in _MODE_BOUNDS:
        return {"valid": False, "J": _SELECTION_SENTINEL, "pass": False}
    required_charge = target_V / (gain * stages)
    chosen_charge = min(charge_cap_V, required_charge)
    crest = gain * stages * chosen_charge
    front_lo, front_hi = _MODE_BOUNDS[mode]["front_us"]
    tail_lo, tail_hi = _MODE_BOUNDS[mode]["tail_us"]
    front_nominal = (front_lo + front_hi) / 2.0
    tail_nominal = (tail_lo + tail_hi) / 2.0
    front_half = (front_hi - front_lo) / 2.0
    tail_half = (tail_hi - tail_lo) / 2.0
    crest_half = 0.03 * target_V
    parts = np.asarray(
        ((crest - target_V) / crest_half, (front_us - front_nominal) / front_half, (tail_us - tail_nominal) / tail_half),
        dtype=float,
    )
    score = float(np.dot(parts, parts)) if np.isfinite(parts).all() else _SELECTION_SENTINEL
    return {
        "valid": bool(math.isfinite(score)),
        "J": score,
        "pass": bool(
            math.isfinite(score)
            and target_V * 0.97 <= crest <= target_V * 1.03
            and front_lo <= front_us <= front_hi
            and tail_lo <= tail_us <= tail_hi
        ),
        "required_charge_V": required_charge,
        "charge_cap_V": charge_cap_V,
        "chosen_charge_V": chosen_charge,
        "crest_V": crest,
        "stored_energy_J": None,
    }


def _fixed_setup_waveform_ranking(rows: Sequence[Mapping[str, Any]], truth: np.ndarray, pred: np.ndarray, mode: str) -> dict[str, Any]:
    """Measure request-level retention under one explicit held-out target.

    Validation rows are grouped by their frozen setup/request group.  Every
    group uses the same deterministic one-megavolt target, so rankings compare
    candidates at a common requested output even when simulation rows were
    labelled at different charge values.  A group contributes to hit/miss and
    regret only when at least one candidate is truly feasible under the profile
    charge/energy cap and legacy waveform limits.
    """

    groups: dict[str, list[int]] = defaultdict(list)
    for index, row in enumerate(rows):
        groups[_request_group(row, index)].append(index)
    group_summaries: list[dict[str, Any]] = []
    true_j_values: list[float] = []
    predicted_j_values: list[float] = []
    candidate_count = 0
    valid_group_count = 0
    feasible_group_count = 0
    true_feasible_candidates = 0
    predicted_pass_candidates = 0
    charge_cap_values: list[float] = []
    missed_counts = {1: 0, 3: 0, 5: 0}
    hit_counts = {1: 0, 3: 0, 5: 0}
    regret_values: dict[int, list[float]] = {1: [], 3: [], 5: []}
    regret_raw_values: dict[int, list[float]] = {1: [], 3: [], 5: []}
    first_pass_ranks: list[int] = []

    for group_id, indices in sorted(groups.items(), key=lambda item: item[0]):
        scored: list[tuple[int, dict[str, Any], dict[str, Any]]] = []
        for index in indices:
            cap_data = _charge_cap_for_row(rows[index])
            if cap_data is None:
                continue
            cap, stages = cap_data
            charge_cap_values.append(cap)
            truth_score = _fixed_target_score(*truth[index], cap, stages, mode, _SELECTION_TARGET_V)
            pred_score = _fixed_target_score(*pred[index], cap, stages, mode, _SELECTION_TARGET_V)
            scored.append((index, truth_score, pred_score))
        candidate_count += len(scored)
        if not scored:
            continue
        valid_group_count += 1
        truth_pass = [item[1]["pass"] for item in scored]
        true_feasible_candidates += int(sum(truth_pass))
        predicted_pass_candidates += int(sum(item[2]["pass"] for item in scored))
        true_j_values.extend(item[1]["J"] for item in scored)
        predicted_j_values.extend(item[2]["J"] for item in scored)
        best_true = min((item[1]["J"] for item in scored if item[1]["pass"]), default=None)
        if best_true is None:
            continue
        feasible_group_count += 1
        ordered = sorted(scored, key=lambda item: (item[2]["J"], _row_key(rows[item[0]], item[0])))
        first_pass = next((rank for rank, item in enumerate(ordered, 1) if item[1]["pass"]), None)
        if first_pass is not None:
            first_pass_ranks.append(first_pass)
        for width in (1, 3, 5):
            top = ordered[:width]
            top_true = [item[1]["J"] for item in top if item[1]["pass"]]
            hit = bool(top_true)
            hit_counts[width] += int(hit)
            missed_counts[width] += int(not hit)
            if top_true:
                raw_regret = max(0.0, min(top_true) - best_true)
                regret_raw_values[width].append(raw_regret)
                regret_values[width].append(raw_regret / max(abs(best_true), 1.0e-12))
        group_summaries.append(dict(group_id=group_id, candidate_count=len(scored), true_feasible_count=int(sum(truth_pass)), first_true_feasible_rank=first_pass))

    coverage_status = "AVAILABLE"
    if valid_group_count < _MIN_GROUP_COVERAGE:
        coverage_status = "INSUFFICIENT_GROUP_COVERAGE"
    elif feasible_group_count == 0:
        coverage_status = "NO_TRUE_FEASIBLE_GROUPS"
    result: dict[str, Any] = {
        "status": "FIXED_SETUP_WAVEFORM_RANKING",
        "target_policy": "FIXED_1MV",
        "target_crest_V": _SELECTION_TARGET_V,
        "group_key_policy": "request_group_id/request_id/group_id/setup_family_id/row_id",
        "candidate_count": candidate_count,
        "group_count": len(groups),
        "valid_group_count": valid_group_count,
        "feasible_group_count": feasible_group_count,
        "groups_coverage_status": coverage_status,
        "groups_coverage_insufficient": coverage_status != "AVAILABLE",
        "minimum_group_coverage": _MIN_GROUP_COVERAGE,
        "true_feasible_candidate_count": true_feasible_candidates,
        "predicted_pass_candidate_count": predicted_pass_candidates,
        "true_pass_rate": float(true_feasible_candidates / candidate_count) if candidate_count else None,
        "predicted_pass_rate": float(predicted_pass_candidates / candidate_count) if candidate_count else None,
        "charge_cap_V": {
            "min": float(np.min(charge_cap_values)) if charge_cap_values else None,
            "max": float(np.max(charge_cap_values)) if charge_cap_values else None,
            "mean": float(np.mean(charge_cap_values)) if charge_cap_values else None,
        },
        "true_J": float(np.mean(true_j_values)) if true_j_values else None,
        "predicted_J": float(np.mean(predicted_j_values)) if predicted_j_values else None,
        "mean_true_J": float(np.mean(true_j_values)) if true_j_values else None,
        "mean_predicted_J": float(np.mean(predicted_j_values)) if predicted_j_values else None,
        "prefix_first_pass": {
            "count": len(first_pass_ranks),
            "mean_rank": float(np.mean(first_pass_ranks)) if first_pass_ranks else None,
            "median_rank": float(np.median(first_pass_ranks)) if first_pass_ranks else None,
        },
        "group_summary_count": len(group_summaries),
        "group_summaries": group_summaries[:32],
        "group_summaries_truncated": len(group_summaries) > 32,
    }
    # Numeric top-level aliases make the selection fields easy to consume while
    # the count/rate forms preserve the denominator for auditability.
    for width in (1, 3, 5):
        denominator = feasible_group_count
        missed_rate = float(missed_counts[width] / denominator) if denominator else None
        hit_rate = float(hit_counts[width] / denominator) if denominator else None
        result[f"missed_feasible@{width}"] = missed_rate
        result[f"missed_feasible@{width}_count"] = missed_counts[width]
        result[f"missed_feasible@{width}_rate"] = missed_rate
        result[f"feasible_hit@{width}"] = hit_rate
        result[f"feasible_hit@{width}_count"] = hit_counts[width]
        result[f"feasible_hit@{width}_rate"] = hit_rate
        result[f"feasiblehit@{width}"] = hit_rate
        normalized_regret = regret_values[width]
        raw_regret = regret_raw_values[width]
        result[f"regret_besttrueJ@{width}"] = float(np.mean(normalized_regret)) if normalized_regret else None
        result[f"regret_besttrueJ@{width}_mean"] = result[f"regret_besttrueJ@{width}"]
        result[f"regret_besttrueJ@{width}_raw_mean"] = float(np.mean(raw_regret)) if raw_regret else None
        result[f"regret_besttrueJ@{width}_count"] = len(normalized_regret)
        result[f"regret_besttrueJ@{width}_unavailable_count"] = max(0, feasible_group_count - len(normalized_regret))
    result["missed_feasible_at_5"] = missed_counts[5]
    result["feasible_hit_at_5"] = hit_counts[5] / feasible_group_count if feasible_group_count else None
    result["mean_regret_at_5"] = float(np.mean(regret_values[5])) if regret_values[5] else None
    result["secondary_gain_order_proxy"] = _pairwise_rank_accuracy(rows, truth, pred)
    return result


def optimization_validation_metrics(rows: Sequence[Mapping[str, Any]], truth: np.ndarray, pred: np.ndarray | None = None, hook: Callable | None = None, *, model: NetworkModel | None = None) -> dict[str, Any]:
    """Extension hook for request-level selection metrics.

    The built-in metric is a fixed-target, fixed-setup group proxy.  ``hook``
    is called only on validation rows during training.  A two-argument hook
    named ``(model, validation_rows)`` can run an independent frozen request
    oracle; its returned metrics are stored separately and may drive the
    validation-only selection key without changing model fitting or test
    access boundaries.
    """

    if pred is None:
        # Convenience form for a future request-level caller that only has
        # predictions; labels remain derived from the immutable validation
        # rows.  The three-argument form is used by the trainer.
        pred = np.asarray(truth, dtype=float)
        truth = _labels(rows)
    primary = _fixed_setup_waveform_ranking(rows, np.asarray(truth, dtype=float), np.asarray(pred, dtype=float), str(rows[0].get("mode", rows[0].get("impulse_type", "LI"))) if rows else "LI")
    if hook is not None:
        try:
            parameters = inspect.signature(hook).parameters.values()
            positional = [p for p in parameters if p.kind in (inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.POSITIONAL_OR_KEYWORD)]
            accepts_varargs = any(p.kind == inspect.Parameter.VAR_POSITIONAL for p in parameters)
        except (TypeError, ValueError):
            positional, accepts_varargs = [], True
        names = [p.name.lower() for p in positional]
        if accepts_varargs or len(positional) >= 3:
            value = hook(rows, truth, pred)
        elif len(positional) == 2 and (
            names[0] in {"model", "candidate", "predictor"}
            or names[1] in {"rows", "validation_rows", "requests", "validation_requests"}
        ):
            # The lead's independent catalog oracle receives the fitted model
            # so it can score a frozen request set without retraining or
            # relying on row-level labels from the training dataset.
            value = hook(model, rows)
        else:
            # Preserve the compact legacy two-argument extension form.
            value = hook(rows, pred)
        if not isinstance(value, Mapping):
            raise TypeError("optimization validation hook must return a mapping")
        hook_metrics = dict(value)
        # A complete oracle with no true-feasible request has no retention
        # denominator.  Keep that fact explicit so a zero miss count cannot
        # be mistaken for perfect retention; selection then falls back to the
        # validation regression evidence for that route.
        status = str(hook_metrics.get("status", "")).upper()
        try:
            request_count = int(hook_metrics.get("request_count", 0))
        except (TypeError, ValueError):
            request_count = 0
        try:
            feasible_request_count = int(hook_metrics.get("feasible_request_count", 0))
        except (TypeError, ValueError):
            feasible_request_count = 0
        if status.startswith("COMPLETE") and request_count > 0 and feasible_request_count > 0:
            hook_metrics.setdefault("feasible_retention_status", "AVAILABLE")
            hook_metrics.setdefault("selection_usable", True)
        elif status.startswith("COMPLETE") and request_count > 0 and feasible_request_count == 0:
            hook_metrics["feasible_retention_status"] = "UNAVAILABLE_NO_TRUE_FEASIBLE_REQUESTS"
            hook_metrics["selection_usable"] = False
            hook_metrics.setdefault("selection_fallback", "REGRESSION_VALIDATION")
            hook_metrics.setdefault(
                "selection_fallback_reason",
                "Oracle requests completed but none had a true feasible candidate; feasible retention and regret are undefined.",
            )
        elif status.startswith(("UNAVAILABLE", "INCOMPLETE")) or request_count < 1:
            hook_metrics["feasible_retention_status"] = "UNAVAILABLE_NO_ORACLE_COVERAGE"
            hook_metrics["selection_usable"] = False
            hook_metrics.setdefault("selection_fallback", "REGRESSION_VALIDATION")
            hook_metrics.setdefault("selection_fallback_reason", "No complete independent request oracle coverage is available for this route.")
        primary["request_level_hook"] = hook_metrics
    else:
        primary["request_level_hook"] = {"status": "NOT_PROVIDED"}
    return primary


def _ordered_group_subset(rows: Sequence[Mapping[str, Any]], fraction: float, seed: int) -> list[dict[str, Any]]:
    if not rows:
        return []
    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for i, row in enumerate(rows):
        groups[_group_key(row, i)].append(dict(row))
    ordered = sorted(groups, key=lambda key: (_stable_fraction(key, seed), key))
    wanted = max(1, int(math.ceil(len(rows) * fraction)))
    selected: list[dict[str, Any]] = []
    for key in ordered:
        selected.extend(groups[key])
        if len(selected) >= wanted:
            break
    return selected


def _candidate_metrics(model: NetworkModel, rows: Sequence[Mapping[str, Any]], mode: str, hook: Callable | None = None, *, return_ood: bool = False):
    if not rows:
        empty = ({"status": "UNAVAILABLE_EMPTY_VALIDATION"}, np.empty((0, 3)))
        return (*empty, np.empty((0,), dtype=bool)) if return_ood else empty
    x = np.asarray([[row["features"][column] for column in model.columns] for row in rows], dtype=float)
    started = time.perf_counter()
    pred = model.predict(x)
    elapsed = time.perf_counter() - started
    ood = model.ood(x)
    truth = _labels(rows)
    report = metric_report(rows, truth, pred, mode, model_ood=ood)
    report["optimization_validation"] = optimization_validation_metrics(rows, truth, pred, hook, model=model)
    report["prediction_seconds"] = elapsed
    report["prediction_rows_per_second"] = float(len(rows) / elapsed) if elapsed > 0 else None
    return (report, pred, ood) if return_ood else (report, pred)


def _selection_key(candidate: Mapping[str, Any]) -> tuple[float, float, float, float, float]:
    """Validation-only lexicographic policy for a feasible screening model.

    The first term protects feasible validation request groups from being
    missed at the optimizer's top-five prefix.  True-J regret then resolves
    candidates, followed by normalized waveform error and throughput.  Missing
    group coverage receives a finite sentinel and is reported in the card;
    the tie-break does not turn a coverage gap into evidence.
    """

    validation = candidate["validation"]
    ranking = validation.get("optimization_validation", {})
    hook_metrics = ranking.get("request_level_hook", {}) if isinstance(ranking, Mapping) else {}
    # An independent frozen-catalog oracle, when supplied by the lead, is the
    # selection evidence.  Dataset-group ranking remains an explicit coverage
    # diagnostic and is never allowed to masquerade as oracle data.
    external = isinstance(hook_metrics, Mapping) and hook_metrics.get("status") not in (None, "NOT_PROVIDED")
    primary_ranking = hook_metrics if external else {}

    def _first_metric(*names: str) -> Any:
        if not isinstance(primary_ranking, Mapping):
            return None
        for name in names:
            if primary_ranking.get(name) is not None:
                return primary_ranking.get(name)
        return None

    missed = _first_metric("missed_feasible@5", "missed_requests@5", "missed_feasible_at_5", "missed_requests_at_5")
    regret = _first_metric(
        "regret_besttrueJ@5",
        "regret_best_true_J@5",
        "regret_besttrueJ_at_5",
        "regret_best_true_J_at_5",
        # OracleValidation reports its fixed top-25 regret because top-5 is
        # already the primary miss gate.
        "mean_regret_at_25",
    )
    coverage_insufficient = bool(
        primary_ranking.get("groups_coverage_insufficient", primary_ranking.get("coverage_insufficient", False))
    ) if isinstance(primary_ranking, Mapping) else True
    if external and isinstance(primary_ranking, Mapping):
        status = str(primary_ranking.get("status", "")).upper()
        if status.startswith("UNAVAILABLE") or status.startswith("INCOMPLETE"):
            coverage_insufficient = True
        if primary_ranking.get("selection_usable") is False:
            coverage_insufficient = True
        if str(primary_ranking.get("feasible_retention_status", "")).upper().startswith("UNAVAILABLE"):
            coverage_insufficient = True
        try:
            coverage_insufficient = coverage_insufficient or int(primary_ranking.get("request_count", 1)) < 1 or int(primary_ranking.get("feasible_request_count", 1)) < 1
        except (TypeError, ValueError):
            coverage_insufficient = True
    if not external:
        coverage_insufficient = True
    if coverage_insufficient or missed is None:
        missed = _SELECTION_SENTINEL
    if coverage_insufficient or regret is None:
        regret = _SELECTION_SENTINEL
    throughput = validation.get("prediction_rows_per_second")
    try:
        throughput_value = float(throughput)
        if not math.isfinite(throughput_value) or throughput_value < 0:
            throughput_value = 0.0
    except (TypeError, ValueError):
        throughput_value = 0.0
    try:
        normalized_error = float(validation.get("selection_score", _SELECTION_SENTINEL))
        if not math.isfinite(normalized_error):
            normalized_error = _SELECTION_SENTINEL
    except (TypeError, ValueError):
        normalized_error = _SELECTION_SENTINEL
    try:
        fit_seconds = float(candidate.get("fit_seconds", _SELECTION_SENTINEL))
        if not math.isfinite(fit_seconds) or fit_seconds < 0:
            fit_seconds = _SELECTION_SENTINEL
    except (TypeError, ValueError):
        fit_seconds = _SELECTION_SENTINEL
    return (float(missed), float(regret), normalized_error, -throughput_value, fit_seconds)


def _selection_evidence(candidate: Mapping[str, Any]) -> dict[str, Any]:
    """Explain whether a route selection used feasible request retention."""

    validation = candidate.get("validation", {})
    ranking = validation.get("optimization_validation", {}) if isinstance(validation, Mapping) else {}
    hook = ranking.get("request_level_hook", {}) if isinstance(ranking, Mapping) else {}
    if not isinstance(hook, Mapping) or hook.get("status") in (None, "NOT_PROVIDED"):
        return {
            "selection_basis": "REGRESSION_VALIDATION_FALLBACK",
            "request_level_oracle_status": "NOT_PROVIDED",
            "feasible_retention_status": "UNAVAILABLE_NO_ORACLE_COVERAGE",
            "selection_uses_feasible_retention": False,
            "reason": "No independent request-level oracle was supplied; normalized validation error is the available selection evidence.",
        }
    status = str(hook.get("status", "")).upper()
    try:
        request_count = int(hook.get("request_count", 0))
    except (TypeError, ValueError):
        request_count = 0
    try:
        feasible_request_count = int(hook.get("feasible_request_count", 0))
    except (TypeError, ValueError):
        feasible_request_count = 0
    retention_status = str(hook.get("feasible_retention_status", "")).upper()
    usable = bool(hook.get("selection_usable", False))
    if status.startswith("COMPLETE") and request_count > 0 and feasible_request_count > 0 and usable and not retention_status.startswith("UNAVAILABLE"):
        return {
            "selection_basis": "INDEPENDENT_REQUEST_ORACLE",
            "request_level_oracle_status": hook.get("status"),
            "request_count": request_count,
            "feasible_request_count": feasible_request_count,
            "feasible_retention_status": "AVAILABLE",
            "selection_uses_feasible_retention": True,
            "missed_feasible_at_5": hook.get("missed_feasible_at_5"),
            "mean_regret_at_25": hook.get("mean_regret_at_25"),
        }
    if status.startswith("COMPLETE") and request_count > 0 and feasible_request_count == 0:
        reason = "Oracle requests completed but none had a true feasible candidate; feasible retention and regret are undefined."
        retention_status = "UNAVAILABLE_NO_TRUE_FEASIBLE_REQUESTS"
    else:
        reason = hook.get("selection_fallback_reason", "Independent oracle coverage is unavailable or incomplete for this route.")
        retention_status = retention_status or "UNAVAILABLE_NO_ORACLE_COVERAGE"
    return {
        "selection_basis": "REGRESSION_VALIDATION_FALLBACK",
        "request_level_oracle_status": hook.get("status"),
        "request_count": request_count,
        "feasible_request_count": feasible_request_count,
        "feasible_retention_status": retention_status,
        "selection_uses_feasible_retention": False,
        "reason": reason,
    }


def _source_path_for_callable(value: Any) -> Path | None:
    """Resolve the source file for a function or callable object."""

    try:
        path = inspect.getsourcefile(value) or inspect.getfile(value)
    except (TypeError, OSError):
        path = None
    if path is None:
        try:
            path = inspect.getsourcefile(type(value)) or inspect.getfile(type(value))
        except (TypeError, OSError):
            path = None
    if not path:
        return None
    candidate = Path(path).resolve()
    return candidate if candidate.is_file() else None


def _hook_provenance(hook: Callable | None, optimization_oracles: str | Path | None) -> dict[str, Any]:
    """Record source hashes for the selection hook and frozen oracle manifest."""

    result: dict[str, Any] = {
        "optimization_validation_hook": "NOT_PROVIDED" if hook is None else f"{type(hook).__module__}.{type(hook).__qualname__}",
    }
    source_path = _source_path_for_callable(hook) if hook is not None else None
    if source_path is not None:
        result["optimization_validation_hook_source_sha256"] = file_hash(source_path)
        try:
            result["optimization_validation_hook_source_path"] = source_path.relative_to(Path(__file__).resolve().parents[1]).as_posix()
        except ValueError:
            result["optimization_validation_hook_source_path"] = str(source_path)
        if source_path.name == "benchmark.py":
            # Keep a stable, named field for the independent catalog oracle;
            # the generic hook fields still describe custom hook modules.
            result["benchmark_hook_source_sha256"] = file_hash(source_path)
    if optimization_oracles is not None:
        oracle_dir = Path(optimization_oracles).resolve()
        manifest_path = oracle_dir / "manifest.json"
        if not manifest_path.is_file():
            raise FileNotFoundError(f"Missing optimization oracle manifest: {manifest_path}")
        result["optimization_oracles_manifest_sha256"] = file_hash(manifest_path)
        try:
            oracle_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"Invalid optimization oracle manifest: {manifest_path}") from exc
        result["optimization_oracles_status"] = oracle_manifest.get("status")
        result["optimization_oracles_purpose"] = oracle_manifest.get("purpose")
    return result


def _route_provenance(
    data_manifest: Mapping[str, Any],
    *,
    optimization_validation_hook: Callable | None = None,
    optimization_oracles: str | Path | None = None,
) -> dict[str, Any]:
    from .physics import source_fingerprint as physics_fingerprint

    # A missing Physics fingerprint is a predictive-contract failure.  Do not
    # manufacture a partial provenance record that could later look valid.
    physics = physics_fingerprint()
    root = Path(__file__).resolve().parent
    result = {
        "data_sha256": data_manifest.get("rows_sha256"),
        "data_manifest_sha256": data_manifest.get("manifest_sha256"),
        "physics_source_fingerprint": physics,
        "predictive_contract_source_fingerprint": source_fingerprint(),
        "training_code_sha256": file_hash(root / "training.py"),
        "registry_code_sha256": file_hash(root / "registry.py"),
        "runtime": runtime_versions(),
    }
    result.update(_hook_provenance(optimization_validation_hook, optimization_oracles))
    return result


def train(
    data_dir: str | Path,
    output_dir: str | Path | None = None,
    *,
    registry_dir: str | Path | None = None,
    seed: int = 20261010,
    optimization_validation_hook: Callable | None = None,
    optimization_oracles: str | Path | None = None,
    staged_fractions: Sequence[float] = (0.25, 0.50, 1.0),
) -> dict[str, Any]:
    """Train and register four candidates per available route.

    Candidate selection reads validation rows only.  If an independent oracle
    hook is supplied, it receives each fitted candidate and the route's
    validation rows; otherwise the fixed-setup group proxy is diagnostic and
    normalized waveform error is used until oracle evidence exists.  All four
    candidates stay fit on the train partition so the lead can run that oracle
    against immutable binaries; only after the validation decision are
    held-out test reports computed.  The command never mutates the input
    dataset.
    """

    if optimization_oracles is not None:
        if optimization_validation_hook is not None:
            raise ValueError("Pass either optimization_validation_hook or optimization_oracles, not both")
        # Import lazily so the ordinary fixture/API path does not require the
        # complete-catalog benchmark dependencies or any oracle files.
        from .benchmark import OracleValidation

        optimization_validation_hook = OracleValidation(optimization_oracles)
    load_started = time.perf_counter()
    rows_all, data_manifest = load_rows(data_dir)
    load_elapsed = time.perf_counter() - load_started
    eligible_rows = [row for row in rows_all if _eligible(row)]
    if not eligible_rows:
        raise ValueError("Dataset contains no eligible labelled rows")
    if output_dir is None:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        output = Path(__file__).resolve().parent.parent / "powernext" / "ml" / "results" / f"networks_v3_{stamp}"
    else:
        output = Path(output_dir)
    if output.exists():
        raise FileExistsError(f"Versioned results directory exists: {output}")
    registry = Path(registry_dir) if registry_dir is not None else Path(__file__).resolve().parent.parent / "powernext" / "ml" / "registry" / "networks_v3"
    # Validate all explicit split identities before deduplication so a
    # repeated response shape cannot hide a train/validation crossing.
    original_assignments = assign_splits(eligible_rows, seed=seed)
    rows, assignments, deduplication, dedup_audit = _deduplicate_training_rows(eligible_rows, original_assignments)
    identity_components = _frozen_group_values(eligible_rows)
    split_records = [
        dict(
            row_id=_row_key(row, i),
            group_id=_group_key(row, i),
            identity_component_id=identity_components[i],
            split=original_assignments[i],
            route=_route(row),
            **dedup_audit[i],
        )
        for i, row in enumerate(eligible_rows)
    ]
    grouped: dict[tuple[str, str, str], list[dict[str, Any]]] = defaultdict(list)
    for row, assignment in zip(rows, assignments):
        copy = dict(row)
        copy["split"] = assignment
        route = _route(copy)
        if None not in route:
            grouped[route].append(copy)
    fixture = data_manifest.get("fixture_only") is True and data_manifest.get("dataset_kind") == "EXPLICIT_TEST_FIXTURE"
    scope = _validate_training_scope(grouped, fixture=fixture)
    output.mkdir(parents=True)
    _json_write(output / "split_assignments.json", split_records)
    route_results: list[dict[str, Any]] = []
    selections: dict[str, str] = {}
    selected_models: dict[str, str] = {}
    provenance = _route_provenance(
        data_manifest,
        optimization_validation_hook=optimization_validation_hook,
        optimization_oracles=optimization_oracles,
    )
    _progress(
        f"dataset loaded rows={len(rows_all)} eligible={len(eligible_rows)} canonical={len(rows)} "
        f"duplicates_removed={deduplication['duplicates_removed']} load_seconds={load_elapsed:.3f}"
    )
    for route in sorted(grouped):
        domain, mode, topology = route
        route_id = f"{domain}:{mode}:{topology}"
        route_rows = grouped[route]
        train_rows = [row for row in route_rows if row["split"] == "train"]
        val_rows = [row for row in route_rows if row["split"] == "validation"]
        test_rows = [row for row in route_rows if row["split"] == "test"]
        _progress(f"route={route_id} start train={len(train_rows)} validation={len(val_rows)} test={len(test_rows)}")
        if not train_rows or not val_rows:
            route_results.append(dict(route_id=route_id, status="INSUFFICIENT_TRAIN_VALIDATION_ROWS", train_rows=len(train_rows), validation_rows=len(val_rows), test_rows=len(test_rows)))
            _json_write(output / f"checkpoint_{domain}_{mode}_{topology}.json", route_results[-1])
            _progress(f"route={route_id} skipped insufficient train/validation rows")
            continue
        # Freeze one deterministic group order per route.  Every candidate
        # must see identical 25/50/100% learning-curve subsets so differences
        # are attributable to formulation/family rather than a hidden sample
        # draw.  Prefix construction makes the default fractions nested.
        staged_subsets = {
            float(fraction): _ordered_group_subset(train_rows, float(fraction), seed)
            for fraction in staged_fractions
        }
        candidates: list[dict[str, Any]] = []
        for formulation in FORMULATIONS:
            for family in FAMILIES:
                model = NetworkModel(domain, mode, topology, formulation, family)
                stages: list[dict[str, Any]] = []
                for fraction in staged_fractions:
                    stage_rows = staged_subsets[float(fraction)]
                    _progress(f"route={route_id} candidate={formulation}/{family} fraction={float(fraction):.2f} start rows={len(stage_rows)}")
                    start = time.perf_counter()
                    model.fit(stage_rows)
                    fit_elapsed = time.perf_counter() - start
                    _progress(f"route={route_id} candidate={formulation}/{family} fraction={float(fraction):.2f} fit_complete=true fit_seconds={fit_elapsed:.3f}")
                    val_report, _ = _candidate_metrics(model, val_rows, mode, optimization_validation_hook)
                    val_report["training_rows"] = len(stage_rows)
                    val_report["fit_seconds"] = fit_elapsed
                    val_report["fit_rows_per_second"] = float(len(stage_rows) / fit_elapsed) if fit_elapsed > 0 else None
                    val_report["serialized_estimate_bytes"] = len(pickle.dumps(model, protocol=pickle.HIGHEST_PROTOCOL))
                    val_report["training_row_ids_sha256"] = _digest([_row_key(row, index) for index, row in enumerate(stage_rows)])
                    val_report["training_group_ids_sha256"] = _digest([_group_key(row, index) for index, row in enumerate(stage_rows)])
                    stages.append(dict(fraction=float(fraction), **val_report))
                    _progress(f"route={route_id} candidate={formulation}/{family} fraction={float(fraction):.2f} validation_complete=true validation_metrics=selection_score:{val_report.get('selection_score')} ood:{val_report.get('ood_count')}")
                final_model = NetworkModel(domain, mode, topology, formulation, family)
                final_fit_started = time.perf_counter()
                final_model.fit(train_rows)
                final_fit_seconds = time.perf_counter() - final_fit_started
                final_val, _ = _candidate_metrics(final_model, val_rows, mode, optimization_validation_hook)
                rank = final_val.get("optimization_validation", {})
                retention = rank.get("secondary_gain_order_proxy", {}).get("retention") if isinstance(rank, Mapping) and isinstance(rank.get("secondary_gain_order_proxy"), Mapping) else None
                candidates.append(dict(
                    model=final_model,
                    formulation=formulation,
                    family=family,
                    validation=final_val,
                    ranking_retention=retention,
                    learning_curve=stages,
                    fit_seconds=final_fit_seconds,
                ))
        # Persist every train-only candidate before looking at the held-out
        # rows.  The lead can therefore run an independent request-level
        # oracle and choose among these immutable binaries without retraining.
        for candidate in candidates:
            candidate["selection_key"] = list(_selection_key(candidate))
            candidate["card"] = register_model(
                candidate["model"],
                provenance=provenance,
                data_sha256=data_manifest.get("rows_sha256"),
                root=registry,
                metrics={"validation": candidate["validation"]},
                training_rows=len(train_rows),
            )
            candidate["model_id"] = candidate["card"]["model_id"]
            _progress(f"route={route_id} candidate={candidate['formulation']}/{candidate['family']} registered model={candidate['model_id']} validation_score={candidate['validation'].get('selection_score')}")
        best = min(candidates, key=lambda item: tuple(item["selection_key"]))
        selected_formulation, selected_family = best["formulation"], best["family"]
        selection_evidence = _selection_evidence(best)
        selections[route_id] = best["model_id"]
        selected_models[route_id] = best["model_id"]
        test_reports: dict[str, Any] = {}
        test_predictions: dict[str, Any] = {}
        if test_rows:
            for candidate in candidates:
                test_report, test_pred, test_ood = _candidate_metrics(candidate["model"], test_rows, mode, None, return_ood=True)
                candidate_key = f"{candidate['formulation']}:{candidate['family']}"
                test_reports[candidate_key] = test_report
                test_predictions[candidate_key] = [
                    dict(row_id=_row_key(row, i), truth=_labels([row])[0].tolist(), prediction=test_pred[i].tolist(), ood=bool(test_ood[i]))
                    for i, row in enumerate(test_rows)
                ]
        selected_test = test_reports.get(f"{selected_formulation}:{selected_family}")
        candidate_reports = []
        for candidate in candidates:
            candidate_key = f"{candidate['formulation']}:{candidate['family']}"
            candidate_reports.append(dict(
                formulation=candidate["formulation"], family=candidate["family"], model_id=candidate["model_id"], selected=(candidate is best), selection_key=candidate["selection_key"], validation=candidate["validation"], learning_curve=candidate["learning_curve"], test=test_reports.get(candidate_key),
            ))
        route_results.append(
            dict(
                route_id=route_id,
                status="COMPLETE",
                selection_policy="validation_only: independent_request_oracle_when_available, missed_feasible_at_5, true_J_regret, grouped_setup_proxy_coverage, tolerance_normalized_error, throughput, fit_time",
                selection_evidence=selection_evidence,
                selected_formulation=selected_formulation,
                selected_family=selected_family,
                train_rows=len(train_rows),
                validation_rows=len(val_rows),
                test_rows=len(test_rows),
                selected_model_id=best["model_id"],
                candidate_models={candidate["formulation"] + ":" + candidate["family"]: candidate["model_id"] for candidate in candidates},
                candidates=candidate_reports,
                selected_test=selected_test,
                test_predictions=test_predictions,
                deduplication=deduplication,
            )
        )
        _json_write(output / f"checkpoint_{domain}_{mode}_{topology}.json", route_results[-1])
        _progress(f"route={route_id} complete selected={best['formulation']}/{best['family']} model={best['model_id']}")
    result_status = "COMPLETE_FIXTURE" if fixture else "COMPLETE"
    result = dict(schema_version="ml_results_v3", status=result_status, scope=scope, data_manifest=data_manifest, provenance=provenance, deduplication=deduplication, routes=route_results, selected_models=selected_models)
    _json_write(output / "results.json", result)
    _json_write(output / "selections.json", selections)
    _json_write(output / "selected_models.json", selected_models)
    run_manifest = dict(
        schema_version="ml_run_manifest_v3",
        status=result_status,
        scope=scope,
        data_sha256=data_manifest.get("rows_sha256"),
        data_manifest_sha256=data_manifest.get("manifest_sha256"),
        deduplication=deduplication,
        result_sha256=file_hash(output / "results.json"),
        split_sha256=file_hash(output / "split_assignments.json"),
        route_count=len(route_results),
        registry_dir=str(registry.resolve()),
        runtime=runtime_versions(),
        source_fingerprint=source_fingerprint(),
        provenance=provenance,
        load_seconds=load_elapsed,
        load_rows_per_second=float(len(rows_all) / load_elapsed) if load_elapsed > 0 else None,
    )
    _json_write(output / "run_manifest.json", run_manifest)
    _progress(f"run complete routes={len(route_results)} output={output}")
    return result


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="PowerNext Phase B v3 ML training")
    sub = parser.add_subparsers(dest="command", required=True)
    command = sub.add_parser("train", help="train four approved candidates per available route")
    command.add_argument("--data-dir", required=True, type=Path)
    command.add_argument("--output-dir", type=Path, required=True)
    command.add_argument("--registry-dir", type=Path)
    command.add_argument("--optimization-oracles", type=Path, help="completed independent validation oracle directory")
    command.add_argument("--seed", type=int, default=20261010)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.command == "train":
        train(args.data_dir, args.output_dir, registry_dir=args.registry_dir, seed=args.seed, optimization_oracles=args.optimization_oracles)
        return 0
    raise AssertionError(args.command)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())


__all__ = [
    "ROUTES",
    "load_rows",
    "write_rows_jsonl",
    "assign_splits",
    "split_assignments",
    "metric_report",
    "boundary_metrics",
    "optimization_validation_metrics",
    "train",
    "main",
]
